import { z } from "zod";
import type { FounderOsContentRegistry } from "./types.js";
const id=z.string().regex(/^[a-z0-9][a-z0-9._-]*$/); const version=z.string().regex(/^\d+\.\d+\.\d+$/); const strings=z.array(z.string());
const goal=z.object({id,version,system:id,title:z.string().min(1),objective:z.string().min(1),recommendedOwnerRole:z.string().min(1),requiredSkills:z.array(id),supportPacks:z.array(z.object({id,version,required:z.boolean().optional()})),requiredCapabilities:z.array(id),inputPaths:strings,outputPaths:strings,acceptanceCriteria:z.array(z.string().min(1)).min(1),cannotCompleteIf:strings,writeScope:strings,externalActionPolicy:z.string().min(1),wakeConditions:strings,nextGoalHints:z.array(id),prerequisites:strings,evidenceRequirements:strings,firm:z.object({required:z.boolean(),buildBefore:z.boolean(),buildAfter:z.boolean()}).optional()}).strict();
const system=z.object({id,version,title:z.string(),purpose:z.string(),stateDependencies:strings,goals:z.array(id),expectedOutputs:strings,wakeConditions:strings,evidenceFeedbackLoop:strings,stopConditions:strings}).strict();
const resource=z.object({id,version,tier:z.enum(["CORE","DOMAIN","GOAL_SPECIFIC"]),path:z.string(),requiredSkills:z.array(id),requiredCapabilities:z.array(id),installedFiles:strings,qualityGates:strings,dependencies:z.array(id),compatibility:z.string().optional()}).strict();
const schema=z.object({registryVersion:version,contentVersion:version,sourceCommit:z.string().min(7),systems:z.array(system),goals:z.array(goal),skills:z.array(z.object({id,version,path:z.string(),provenance:strings.optional()}).strict()),resources:z.array(resource),firmSchemas:z.array(z.object({id,version,path:z.string()}).strict()),migration:z.object({legacyAdapter:z.string(),managerAdapter:z.literal("hermes_local"),executionAdapter:z.literal("jules"),provenance:z.string()}).optional()}).strict();
function unique(items:{id:string}[],kind:string){const seen=new Set<string>();for(const item of items){if(seen.has(item.id))throw new Error(`Duplicate ${kind} id: ${item.id}`);seen.add(item.id)}}
export function validateContentRegistry(input:unknown):FounderOsContentRegistry{const r=schema.parse(input); unique(r.systems,"system");unique(r.goals,"goal");unique(r.skills,"skill");unique(r.resources,"resource");unique(r.firmSchemas,"Firm schema");const systems=new Set(r.systems.map(x=>x.id)),skills=new Set(r.skills.map(x=>x.id)),resources=new Set(r.resources.map(x=>x.id)),goals=new Set(r.goals.map(x=>x.id));for(const g of r.goals){if(!systems.has(g.system))throw new Error(`Goal ${g.id} references unknown system ${g.system}`);for(const x of g.requiredSkills)if(!skills.has(x))throw new Error(`Goal ${g.id} references missing skill ${x}`);for(const x of g.supportPacks)if(x.required!==false&&!resources.has(x.id))throw new Error(`Goal ${g.id} references missing resource ${x.id}`)}for(const s of r.systems)for(const x of s.goals)if(!goals.has(x))throw new Error(`System ${s.id} references missing goal ${x}`);const visiting=new Set<string>(),done=new Set<string>();const byId=new Map(r.resources.map(x=>[x.id,x]));function visit(x:string){if(visiting.has(x))throw new Error(`Cyclic resource dependency at ${x}`);if(done.has(x))return;const item=byId.get(x);if(!item)throw new Error(`Missing resource dependency ${x}`);visiting.add(x);item.dependencies.forEach(visit);visiting.delete(x);done.add(x)}r.resources.forEach(x=>visit(x.id));return r as FounderOsContentRegistry}
export async function loadContentRegistry(reader:{read(path:string):Promise<string|null>},root="company-package"){const raw=await reader.read(`${root}/registry.json`);if(!raw)throw new Error("FounderOS content registry is missing");return validateContentRegistry(JSON.parse(raw))}
