import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { BMC_BLOCKS, bmcResourcePacks, businessModelDecision, businessModelSystem, canvasFingerprint, compileBusinessModelCanvasTemplate, compileBusinessModelRisks, compileCanvas, compileCanvasArtifacts, deriveEntryConfidence, deriveEntryStatus, evaluateCanvas, validateCanvas, type BmcBlock, type BmcCompileInput, type BmcEntryInput } from "../services/business-model-canvas.js";
const fixtures = JSON.parse(readFileSync(new URL("./fixtures/business-model/scenarios.json", import.meta.url), "utf8"));
const evidence = ["problem-1", "problem-2", "segment-1-e", "value-1", "value-2", "value-3", "channel-1", "payment-1", "cost-1", "usage-1", "retention-1", "partner-1", "activity-1", "resource-1"];
const entry = (statement: string, evidenceIds: string[] = [], extra: Partial<BmcEntryInput> = {}): BmcEntryInput => ({ statement, evidenceIds, assumptionIds: [], contradictionIds: [], sourceArtifacts: evidenceIds.map((id) => `evidence/${id}.md`), ...extra });
const unknown = () => entry("UNKNOWN");
const baseBlocks = (): Record<BmcBlock, BmcEntryInput[]> => ({ customerSegments: [entry("Accessibility-led SME product teams", ["problem-1", "problem-2", "segment-1-e"], { segmentId: "segment-1", role: "BUYER", sourceKinds: ["interview", "commercial", "usage"] })], valuePropositions: [entry("Find accessibility friction before launch", ["value-1", "value-2", "value-3"], { segmentId: "segment-1", offerId: "offer-1", sourceKinds: ["customer", "behavior", "outcome"] })], channels: [entry("Founder outreach", ["channel-1"], { channelType: "ACQUISITION", requestedStatus: "HYPOTHESIS" })], customerRelationships: [entry("Founder-led onboarding", ["usage-1"], { relationshipStatus: "CURRENT" })], revenueStreams: [entry("Paid recurring accessibility review", ["payment-1"], { segmentId: "segment-1", offerId: "offer-1", revenueState: "RECEIVED" })], keyResources: [entry("Running MVP", ["resource-1"], { resourceStatus: "CURRENT" })], keyActivities: [entry("Operate review workflow", ["activity-1"])], keyPartners: [unknown()], costStructure: [entry("Manual support and compute", ["cost-1"], { classification: "MEASURED" })] });
const input = (blocks = baseBlocks()): BmcCompileInput => ({ companyId: "company-1", canvasId: "bmc-1", version: "1", sourceStateVersion: "firm:abc123", goalId: "goal-1", projectId: "project-1", blocks, openQuestions: ["Which scalable acquisition channel works?"], staleDependencies: [], knownEvidenceIds: evidence, knownAssumptionIds: ["partner-assumption"], knownContradictionIds: ["contradiction-1"], knownSegmentIds: ["segment-1"], knownOfferIds: ["offer-1"], verifiedReceivedRevenueEvidenceIds: ["payment-1"], economicCostEvidenceIds: ["cost-1"], compiledAt: new Date("2026-09-17T00:00:00Z") });

describe("evidence-backed Business Model Canvas", () => {
  it("maps the native Business Model Synthesis Project, Goal, architect, support packs, and finance handoff", () => { expect(businessModelSystem.title).toBe("Business Model Synthesis"); expect(compileBusinessModelCanvasTemplate.recommendedOwnerRole).toBe("business model architect"); expect(compileBusinessModelCanvasTemplate.prerequisites).toEqual(["analyze-unit-economics accepted"]); expect(compileBusinessModelCanvasTemplate.nextGoalHints).toEqual(["compile-bpw-financial-plan"]); expect(compileBusinessModelCanvasTemplate.requiredSkills).toContain("bpw-business-model-canvas"); expect(bmcResourcePacks.map((pack) => pack.id)).toEqual(["bmc.standard", "bpw.bmc"]); });
  it("always emits the canonical nine-block structure without fabricating unknown partners", () => { const canvas = compileCanvas(input()); expect(Object.keys(canvas.blocks)).toEqual([...BMC_BLOCKS]); expect(canvas.blocks.keyPartners.entries[0]).toMatchObject({ statement: "UNKNOWN", status: "UNKNOWN", confidence: "LOW" }); });
  it("derives maturity and confidence from evidence count, diversity, contradictions, and staleness", () => { const strong = entry("strong", ["a", "b", "c"], { sourceKinds: ["customer", "commercial", "behavior"] }); expect(deriveEntryStatus(strong)).toBe("VALIDATED"); expect(deriveEntryConfidence(strong)).toBe("HIGH"); const stale = { ...strong, stale: true }; expect(deriveEntryStatus(stale)).toBe("EARLY_EVIDENCE"); expect(deriveEntryConfidence(stale)).toBe("LOW"); expect(deriveEntryStatus({ ...strong, contradictionIds: ["c-1"] })).toBe("CONTRADICTED"); });
  it("preserves conflicting ICP evidence and lowers confidence", () => { const value = input(); value.blocks.customerSegments[0].contradictionIds = ["contradiction-1"]; const canvas = compileCanvas(value); expect(canvas.blocks.customerSegments.entries[0]).toMatchObject({ status: "CONTRADICTED", confidence: "LOW", contradictionIds: ["contradiction-1"] }); });
  it("reconciles received revenue with verified commercial/payment evidence", () => { expect(validateCanvas(input()).pass).toBe(true); const invalid = input(); invalid.blocks.revenueStreams[0].evidenceIds = ["value-1"]; expect(validateCanvas(invalid).failures).toContain("revenueStreams: received revenue does not reconcile to verified payment evidence"); });
  it("does not promote listed, quoted, or LOI evidence into received revenue", () => { const hypothetical = input(); hypothetical.blocks.revenueStreams = [entry("Listed price", ["value-1"], { revenueState: "HYPOTHESIZED", requestedStatus: "HYPOTHESIS", offerId: "offer-1" })]; const canvas = compileCanvas(hypothetical); expect(canvas.blocks.revenueStreams.entries[0].status).not.toBe("VALIDATED"); expect(validateCanvas(hypothetical, canvas).pass).toBe(true); });
  it("reconciles Cost Structure with Unit Economics and exposes manual-support weakness", () => { const invalid = input(); invalid.blocks.costStructure[0].evidenceIds = ["usage-1"]; expect(validateCanvas(invalid).failures).toContain("costStructure: cost does not reconcile to unit-economics evidence"); const risks = compileBusinessModelRisks(compileCanvas(input())); expect(risks.some((risk) => risk.block === "keyPartners")).toBe(true); });
  it("requires ICP and offer/value referential integrity", () => { const invalidSegment = input(); invalidSegment.blocks.customerSegments[0].segmentId = "invented"; expect(validateCanvas(invalidSegment).failures).toContain("customerSegments: unresolved segment invented"); const invalidOffer = input(); invalidOffer.blocks.valuePropositions[0].offerId = "invented"; expect(validateCanvas(invalidOffer).failures).toContain("valuePropositions: unresolved offer invented"); });
  it("rejects synthetic validation and nine boxes of unsupported prose", () => { const synthetic = input(); synthetic.blocks.channels[0] = entry("Synthetic channel", ["channel-1", "problem-1"], { synthetic: true }); expect(validateCanvas(synthetic).pass).toBe(false); const prose = Object.fromEntries(BMC_BLOCKS.map((block) => [block, [entry(`Generic ${block}`)]])) as Record<BmcBlock, BmcEntryInput[]>; const result = validateCanvas(input(prose)); expect(result.pass).toBe(false); expect(result.failures.length).toBeGreaterThan(0); });
  it("compiles linked business-model risks and gap-closing registered Goals", () => { const risks = compileBusinessModelRisks(compileCanvas(input())); expect(risks).toContainEqual(expect.objectContaining({ block: "keyPartners", recommendation: "compile-business-model-canvas" })); expect(businessModelDecision(compileCanvas(input()), risks)).toBe("VALIDATE_CHANNEL"); });
  it("produces concise YAML, Markdown, and risk artifacts without treating itself as evidence", () => { const canvas = compileCanvas(input()), artifacts = compileCanvasArtifacts(canvas); expect(Object.keys(artifacts)).toEqual(["business-case/BUSINESS_MODEL_CANVAS.yaml", "business-case/BUSINESS_MODEL_CANVAS.md", "business-case/BUSINESS_MODEL_RISKS.md"]); expect(artifacts["business-case/BUSINESS_MODEL_CANVAS.md"]).toContain("Source state: firm:abc123"); expect(artifacts["business-case/BUSINESS_MODEL_CANVAS.md"]).toContain("contradictions"); });
  it("runs deterministic validation and Firm before Hermes", async () => { const order: string[] = [], value = input(), canvas = compileCanvas(value), validation = validateCanvas(value, canvas), risks = compileBusinessModelRisks(canvas); await evaluateCanvas(validation, canvas, risks, { firmBuild: async (phase) => { order.push(`firm-${phase}`); return { success: true }; }, writeFirm: async () => { order.push("firm-write"); }, judge: async () => { order.push("hermes"); return { verdict: "ACCEPT" }; } }); expect(order).toEqual(["firm-before", "firm-write", "firm-after", "hermes"]); });
  it("does not let Hermes invent evidence after a deterministic failure", async () => { const judge = vi.fn(), firmBuild = vi.fn(), value = input(); value.blocks.revenueStreams[0].evidenceIds = ["value-1"]; const canvas = compileCanvas(value), result = await evaluateCanvas(validateCanvas(value, canvas), canvas, compileBusinessModelRisks(canvas), { judge, firmBuild }); expect(result.accepted).toBe(false); expect(judge).not.toHaveBeenCalled(); expect(firmBuild).not.toHaveBeenCalled(); });
  it("fingerprints unchanged source state for idempotent recompilation", () => { expect(canvasFingerprint(input())).toBe(canvasFingerprint(input())); const changed = input(); changed.sourceStateVersion = "firm:new"; expect(canvasFingerprint(changed)).not.toBe(canvasFingerprint(input())); });
  it("contains required scenarios A-J", () => { expect(fixtures.map((scenario: { id: string }) => scenario.id)).toEqual(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]); });
});
