import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { BUSINESS_PLAN_CHAPTERS, bpwBusinessPlanResourcePack, businessPlanFingerprint, businessPlanSystem, chapterReadiness, compileBusinessPlan, compileBusinessPlanArtifacts, compileBusinessPlanTemplate, evaluateBusinessPlan, validateBusinessPlan, validateEditorialRevision, type BusinessPlanChapterId, type BusinessPlanInput, type PlanStatement } from "../services/business-plan.js";
const fixtures = JSON.parse(readFileSync(new URL("./fixtures/business-plan/scenarios.json", import.meta.url), "utf8"));
const statement = (statementId: string, text: string, extra: Partial<PlanStatement> = {}): PlanStatement => ({ statementId, text, statementType: "OBSERVED_FACT", evidenceIds: [`e-${statementId}`], sourceArtifactIds: [`evidence/${statementId}`], assumptionIds: [], calculationIds: [], contradictionIds: [], freshness: "CURRENT", confidence: "HIGH", ...extra });
const chapters = () => Object.fromEntries(BUSINESS_PLAN_CHAPTERS.map((id) => [id, id === "executive-summary" ? [] : [statement(id, `${id} is supported`)]])) as Record<BusinessPlanChapterId, PlanStatement[]>;
const input = (): BusinessPlanInput => { const c = chapters(); return { companyId: "company-1", goalId: "goal-1", projectId: "project-1", planId: "plan-1", version: "1", sourceStateVersion: "firm:1", bpwResourceVersion: "1.0.0", compiledAt: new Date("2026-09-18T00:00:00Z"), chapters: c, executiveSummaryClaimIds: ["product-service", "financial-planning"], knownEvidenceIds: BUSINESS_PLAN_CHAPTERS.filter((id) => id !== "executive-summary").map((id) => `e-${id}`), knownAssumptionIds: ["a-legal"], knownCalculationIds: ["calc-revenue"], knownContradictionIds: ["contra-market"], knownTeamFactIds: ["team-founder"], knownCapabilityIds: ["cap-mvp"], financialMetrics: { revenue: 1200 }, marketMetrics: { sam: 800 }, sources: [{ sourceId: "source-1", title: "Customer evidence", publisher: "Company", evidenceType: "CUSTOMER", claimsUsed: ["product-service"] }], risks: [{ riskId: "risk-1", description: "Channel scale unproven", impact: "Revenue forecast", evidenceIds: [], assumptionIds: [], affectedChapter: "marketing-go-to-market", mitigationGoal: "validate-demand", status: "OPEN" }], staleDependencies: [] }; };

describe("BPW business plan compiler", () => {
  it("maps native Project, Goal, Business Plan Editor, BPW pack and Pitch handoff", () => { expect(businessPlanSystem.title).toBe("Business Plan Compilation"); expect(compileBusinessPlanTemplate.recommendedOwnerRole).toBe("business plan editor"); expect(compileBusinessPlanTemplate.prerequisites).toEqual(["compile-bpw-financial-plan accepted"]); expect(compileBusinessPlanTemplate.nextGoalHints).toEqual(["compile-pitch"]); expect(bpwBusinessPlanResourcePack.id).toBe("bpw.business-plan"); });
  it("compiles all canonical chapters and derives the Executive Summary last", () => { const plan = compileBusinessPlan(input()); expect(Object.keys(plan.chapters)).toEqual([...BUSINESS_PLAN_CHAPTERS]); expect(plan.chapters["executive-summary"].statements.map((s) => s.statementId)).toEqual(["summary:product-service", "summary:financial-planning"]); expect(validateBusinessPlan(input(), plan).pass).toBe(true); });
  it("rejects an Executive Summary fact absent from the body", () => { const value = input(); value.executiveSummaryClaimIds.push("invented-growth"); expect(validateBusinessPlan(value).failures).toContain("Executive Summary claim invented-growth is not present in a substantive chapter"); });
  it("requires claim evidence, assumption, or calculation provenance and retains contradictions", () => { const value = input(); value.chapters["market-analysis"][0] = statement("market-analysis", "Market claims conflict", { evidenceIds: [], contradictionIds: ["contra-market"] }); const result = validateBusinessPlan(value); expect(result.failures).toContain("market-analysis: unsupported material statement"); expect(compileBusinessPlan(value).overall.contradictions).toContain("contra-market"); });
  it("reconciles financial and market numbers exactly", () => { const value = input(); value.chapters["financial-planning"][0] = statement("financial-planning", "Revenue is 1,300", { calculationIds: ["calc-revenue"], financialMetricId: "revenue", financialValue: 1300 }); value.chapters["market-analysis"][0] = statement("market-analysis", "Reachable market is 900", { marketMetricId: "sam", marketValue: 900 }); expect(validateBusinessPlan(value).failures).toEqual(expect.arrayContaining(["financial-planning: financial value does not reconcile", "market-analysis: market value does not reconcile"])); });
  it("does not invent team facts, product capabilities, or legal form", () => { const value = input(); value.chapters["founding-team"][0] = statement("founding-team", "Invented advisor", { teamFactId: "unknown-person" }); value.chapters["product-service"][0] = statement("product-service", "Roadmap feature exists", { capabilityId: "future-feature", capabilityStatus: "CURRENT" }); value.chapters["company-organisation"][0] = statement("legal-form", "Legal form requires founder input", { statementType: "UNKNOWN", evidenceIds: [] }); const failures = validateBusinessPlan(value).failures; expect(failures).toContain("founding-team: unregistered team fact"); expect(failures).toContain("product-service: unregistered product capability"); expect(chapterReadiness(value.chapters["company-organisation"])).toBe("BLOCKED"); });
  it("blocks unauthorized customer data and synthetic factual evidence", () => { const value = input(); value.chapters["product-service"][0] = statement("product-service", "Named customer email", { containsPrivateCustomerData: true }); value.chapters["marketing-go-to-market"][0] = statement("marketing-go-to-market", "Synthetic demand", { synthetic: true }); expect(validateBusinessPlan(value).failures).toEqual(expect.arrayContaining(["product-service: private customer data is not authorized for disclosure", "marketing-go-to-market: synthetic material cannot support a factual statement"])); });
  it("marks assumption-heavy and stale chapters without polishing away gaps", () => { const assumed = [statement("a", "Unverified channel", { statementType: "HYPOTHESIS", evidenceIds: [], assumptionIds: ["a-legal"] })]; expect(chapterReadiness(assumed)).toBe("ASSUMPTION_HEAVY"); expect(chapterReadiness([statement("s", "Old market", { freshness: "STALE" })])).toBe("STALE"); });
  it("rejects editorial claims and changed financial figures", () => { const source = [statement("revenue", "Revenue is 1,200 EUR")]; expect(validateEditorialRevision(source, [{ statementId: "new", text: "Rapid growth" }]).pass).toBe(false); expect(validateEditorialRevision(source, [{ statementId: "revenue", text: "Revenue is 2,000 EUR" }]).failures).toContain("revenue: editorial output changed material numbers"); });
  it("emits the canonical artifact set and truthful NOT_RENDERED boundary", () => { const artifacts = compileBusinessPlanArtifacts(input()); expect(Object.keys(artifacts)).toHaveLength(6); expect(artifacts["business-case/business-plan/READINESS.yaml"]).toContain("NOT_RENDERED"); expect(artifacts["business-case/business-plan/CLAIM_EVIDENCE_MAP.yaml"]).toContain("evidenceIds"); });
  it("runs deterministic validation and Firm before Hermes", async () => { const order: string[] = [], value = input(), plan = compileBusinessPlan(value); await evaluateBusinessPlan(validateBusinessPlan(value, plan), plan, { firmBuild: async (phase) => { order.push(`firm-${phase}`); return { success: true }; }, writeFirm: async () => { order.push("firm-write"); }, judge: async () => { order.push("hermes"); return { verdict: "ACCEPT" }; } }); expect(order).toEqual(["firm-before", "firm-write", "firm-after", "hermes"]); });
  it("never lets Hermes override missing evidence", async () => { const value = input(), judge = vi.fn(); value.chapters["market-analysis"][0].evidenceIds = []; await evaluateBusinessPlan(validateBusinessPlan(value), compileBusinessPlan(value), { judge }); expect(judge).not.toHaveBeenCalled(); });
  it("fingerprints source state for idempotency and covers scenarios A-L", () => { expect(businessPlanFingerprint(input())).toBe(businessPlanFingerprint(input())); const changed = input(); changed.sourceStateVersion = "firm:2"; expect(businessPlanFingerprint(changed)).not.toBe(businessPlanFingerprint(input())); expect(fixtures.map((x: { id: string }) => x.id)).toEqual("ABCDEFGHIJKL".split("")); });
});
