import { describe, expect, it } from "vitest";
import scenarios from "./fixtures/commercial-validation/scenarios.json";
import { assessCommercialEvidence, buildProspectUniverseTemplate, compileSalesViews, COMMITMENT_STRENGTH, prospectIdentity, prospectingSystem, validateCommercialCommitmentTemplate, validateProspect } from "../services/commercial-validation.js";

describe("prospecting and commercial validation",()=>{
 const prospect={prospectId:"p-1",accountName:"Acme",canonicalDomain:"acme.example",qualification:"QUALIFIED" as const,qualificationRationale:[{criterion:"segment",status:"MATCH" as const,evidenceIds:["icp-1"]}],fieldProvenance:[{field:"accountName",value:"Acme",source:"registry:1",retrievedAt:"2026-09-15",confidence:"high"},{field:"canonicalDomain",value:"acme.example",source:"registry:1",retrievedAt:"2026-09-15",confidence:"high"}]};
 it("uses canonical systems, goals, and skills",()=>{expect(prospectingSystem.id).toBe("prospecting");expect(buildProspectUniverseTemplate.requiredSkills).toContain("waterfall-prospect-sourcing");expect(validateCommercialCommitmentTemplate.requiredSkills).toContain("sales-second-brain")});
 it("validates provenance and deterministic identity",()=>{expect(validateProspect(prospect)).toEqual({pass:true,failures:[]});expect(prospectIdentity(prospect)).toBe("acme.example")});
 it("rejects invented contacts and suppresses opted-out prospects",()=>{expect(validateProspect({...prospect,contactRef:"guessed:ceo@acme.example",qualification:"OUTREACH_READY",suppressed:true,fieldProvenance:[...prospect.fieldProvenance,{field:"contactRef",value:"x",source:"ai",retrievedAt:"2026-09-15",confidence:"low"}]}).pass).toBe(false)});
 it("orders interest below commercial commitment",()=>{expect(COMMITMENT_STRENGTH.REPLY).toBeLessThan(COMMITMENT_STRENGTH.QUOTE_REQUEST);expect(COMMITMENT_STRENGTH.LOI).toBeLessThan(COMMITMENT_STRENGTH.PAYMENT)});
 it("distinguishes realistic scenarios A-G",()=>{expect(assessCommercialEvidence(scenarios.A.signals as any).pass).toBe(false);expect(assessCommercialEvidence(scenarios.B.signals as any).pass).toBe(false);expect(assessCommercialEvidence(scenarios.C.signals as any).pass).toBe(false);expect(assessCommercialEvidence(scenarios.D.signals as any).pass).toBe(true);expect(assessCommercialEvidence(scenarios.E.signals as any).strongest?.kind).toBe("LOI");expect(assessCommercialEvidence(scenarios.F.signals as any).pass).toBe(true);expect(assessCommercialEvidence(scenarios.G.signals as any).pass).toBe(false)});
 it("does not accept draft/sent quote or unverified payment",()=>{expect(assessCommercialEvidence([{kind:"QUOTE_REQUEST",sourceRef:"quote:1",quoteStatus:"SENT",qualifiedProspect:true}]).pass).toBe(false);const payment=assessCommercialEvidence([{kind:"PAYMENT",sourceRef:"note:1",qualifiedProspect:true}]);expect(payment.pass).toBe(false);expect(payment.hardFailure).toBe(true)});
 it("compiles source-linked Sales Second Brain views",()=>{const views=compileSalesViews({prospects:[prospect],interactions:[{interactionId:"i-1",prospectId:"p-1",channel:"email",sourceRef:"email:1",occurredAt:"2026-09-15",objection:"Price",nextAction:"Send scoped quote"}],signals:[{kind:"QUOTE_REQUEST",sourceRef:"email:1",qualifiedProspect:true}]});expect(views["sales/OBJECTION_LIBRARY.md"]).toContain("source email:1");expect(views["business-case/PRICING_EVIDENCE.md"]).toContain("QUOTE_REQUEST")});
});
