import { describe, expect, it } from "vitest";
import type { Db } from "@paperclipai/db";
import { agents, companies, companyJulesSources, companyRepositoryBindings, founderosBootstraps, goals, goalTemplateInstances, issues, julesProfileSources, projects } from "@paperclipai/db";
import { firmService } from "../services/firm.js";
import { FOUNDEROS_CONTEXT_VERSION, founderOsBootstrapFiles, founderOsBootstrapService, missingBootstrapFiles } from "../services/founderos-bootstrap.js";
function fakeDb() {
 const rows=new Map<unknown,any[]>([[companies,[{id:"company-1",name:"Acme"}]]]); let id=0;
 const select=()=>{ let selected:any[]=[]; const q:any={from:(t:unknown)=>{selected=rows.get(t)??[];return q},where:()=>q,limit:()=>q,orderBy:()=>q,then:(ok:any,bad:any)=>Promise.resolve(selected).then(ok,bad)}; return q };
 const db:any={select,transaction:(fn:any)=>fn(db),insert:(table:unknown)=>({values:(value:any)=>{const vals=Array.isArray(value)?value:[value]; const made=vals.map((v)=>({id:v.id??`id-${++id}`,...v})); const target=rows.get(table)??[]; rows.set(table,target); const op:any={onConflictDoNothing:()=>op,onConflictDoUpdate:()=>op,returning:async()=>{target.push(...made);return made},then:(ok:any)=>Promise.resolve(target.push(...made)).then(ok)}; return op}}),update:(table:unknown)=>({set:(patch:any)=>({where:()=>{for(const row of rows.get(table)??[])Object.assign(row,patch); const op:any={returning:async()=>rows.get(table)??[],then:(ok:any)=>Promise.resolve(undefined).then(ok)}; return op}})})};
 return {db:db as Db,rows};
}
describe("FounderOS company bootstrap",()=>{
 it("defines versioned, secret-free Firm and .founderos structures",()=>{const files=founderOsBootstrapFiles("commit-1"); expect(files[".founderos/JULES_CONTEXT.md"]).toContain(FOUNDEROS_CONTEXT_VERSION); expect(files["firm/schemas/evidence.firm"]).toContain("entity evidence"); expect(Object.keys(files)).toContain("firm/company.firm"); expect(JSON.stringify(files)).not.toMatch(/AIza|Bearer [A-Za-z0-9]/);});
 it("preserves existing files and only proposes missing structure",()=>{const missing=missingBootstrapFiles(["AGENTS.md","firm/company.firm"],"commit-1"); expect(missing).not.toHaveProperty("AGENTS.md"); expect(missing).not.toHaveProperty("firm/company.firm"); expect(missing).toHaveProperty(".founderos/JULES_CONTEXT.md");});
 it("never initializes upstream Firm as company knowledge",async()=>{await expect(firmService({} as Db).initFirm("company-1",null)).rejects.toThrow(/repository binding is required/);});
 it("instantiates the deployable native organization and Goal catalog once",async()=>{const store=fakeDb(); const service=founderOsBootstrapService(store.db,{contentCommit:"commit-1",sourceResolver:{resolve:async()=>({source:"sources/acme",profileId:"profile-1",accessible:true})}}); const repo={repository:"acme/company",repositoryId:"42",defaultBranch:"main",commitSha:"abc",paths:["company/OVERVIEW.md","website/index.html",...Object.keys(founderOsBootstrapFiles("commit-1"))],readText:async()=>"A concept, with no claimed traction."}; const first=await service.bootstrap("company-1",repo); const second=await service.bootstrap("company-1",repo); expect(second.idempotent).toBe(true); expect(second.nativeIds).toEqual(first.nativeIds); expect(store.rows.get(companyRepositoryBindings)).toHaveLength(1); expect(store.rows.get(companyJulesSources)).toHaveLength(1); expect(store.rows.get(julesProfileSources)?.[0].profileId).toBe("profile-1"); const gs=store.rows.get(goals)??[]; expect(gs.find((g)=>g.id===first.nativeIds.visionGoalId)?.level).toBe("company"); expect(gs.filter((g)=>g.parentId===first.nativeIds.visionGoalId).length).toBeGreaterThan(20); expect((store.rows.get(goalTemplateInstances)??[]).length).toBe(gs.length-1); const as=store.rows.get(agents)??[]; expect(as.filter((a)=>a.reportsTo===first.nativeIds.managerAgentId)).toHaveLength(10); expect(as.filter((a)=>a.adapterType==="jules").every((a)=>a.adapterConfig.repository==="acme/company"&&a.adapterConfig.source==="sources/acme")).toBe(true); const initial=(store.rows.get(issues)??[])[0]; expect((store.rows.get(projects)??[])[0].goalId).toBe(initial.goalId); expect(initial).toMatchObject({projectId:first.nativeIds.projectId}); expect(store.rows.get(founderosBootstraps)).toHaveLength(1);});
 it("surfaces missing seed/source readiness and pauses Jules workers",async()=>{const store=fakeDb(); const service=founderOsBootstrapService(store.db,{contentCommit:"commit-1",sourceResolver:{resolve:async()=>({source:"",accessible:false,reason:"not authorized"})}}); const result=await service.bootstrap("company-1",{repository:"acme/company",defaultBranch:"main",commitSha:"abc",paths:[],readText:async()=>null}); expect(result.readiness).toMatch(/Missing company/); expect((store.rows.get(issues)??[])[0].status).toBe("blocked"); const workers=(store.rows.get(agents)??[]).filter((agent)=>agent.adapterType==="jules");expect(workers.every((agent)=>agent.status==="paused"&&agent.pauseReason.includes("Jules source"))).toBe(true);});
});
