import { describe, expect, it } from "vitest";
import { validateFounderOsResult } from "../services/founderos-validation/index.js";
import type { DeterministicValidationInput } from "../services/founderos-validation/types.js";
const base = (): DeterministicValidationInput => ({ companyId: "c", goalId: "g", projectId: "p", issueId: "i", agentId: "a", paperclipRunId: "r", julesSessionId: "s", repository: "acme/firm", branch: "work", baseBranch: "main", commitSha: "abc", requirePullRequest: true, requiredOutputs: ["business-case/result.json", "evidence/research/**"], outputPaths: ["business-case/**", "evidence/research/**"], writeScope: ["business-case/**", "evidence/research/**"], files: [{ path: "business-case/result.json", content: "{\"ok\":true}" }, { path: "evidence/research/source.yml", content: "id: EV-1\ntype: interview" }], pullRequest: { exists: true, repository: "acme/firm", baseBranch: "main", headCommit: "abc", changedFiles: ["business-case/result.json", "evidence/research/source.yml"], checks: [{ name: "test", status: "success" }] }, requiredChecks: ["test"], requiredEvidenceIds: ["EV-1"], reportedEvidenceIds: ["EV-1"], quantitativeClaims: [{ claim: "20 interviews", evidenceIds: ["EV-1"] }] });
describe("deterministic FounderOS validation", () => {
  it("passes a valid result", () => expect(validateFounderOsResult(base()).status).toBe("PASS"));
  it("fails missing output and invalid JSON/YAML", () => { const x=base(); x.requiredOutputs.push("missing.md"); x.files[0]!.content="{"; x.files[1]!.content="\tbad"; const r=validateFounderOsResult(x); expect(r.failed.map(f=>f.code)).toEqual(expect.arrayContaining(["required_output","json_parse","yaml_parse"])); });
  it("hard-fails wrong repository and write-scope violations", () => { const x=base(); x.pullRequest!.repository="other/repo"; x.pullRequest!.changedFiles.push("website/index.html"); const r=validateFounderOsResult(x); expect(r.hardFailure).toBe(true); expect(r.failed.map(f=>f.code)).toEqual(expect.arrayContaining(["repository","write_scope"])); });
  it("redacts a known secret finding", () => { const x=base(); x.knownSecretValues=["super-secret-value"]; x.files.push({path:"business-case/leak.txt",content:"super-secret-value"}); x.pullRequest!.changedFiles.push("business-case/leak.txt"); const r=validateFounderOsResult(x); expect(r.hardFailure).toBe(true); expect(JSON.stringify(r)).not.toContain("super-secret-value"); expect(r.failed.find(f=>f.code==="secret_leak")?.message).toContain("redacted"); });
  it("blocks pending CI and fails required CI", () => { const pending=base(); pending.pullRequest!.checks[0]!.status="pending"; expect(validateFounderOsResult(pending).status).toBe("BLOCKED"); const failing=base(); failing.pullRequest!.checks[0]!.status="failure"; expect(validateFounderOsResult(failing).status).toBe("FAIL"); });
  it("hard-fails Firm build and wrong workspace", () => { const x=base(); x.firm={required:true,buildPassed:false,workspaceRepository:"upstream/firm"}; expect(validateFounderOsResult(x).hardFailure).toBe(true); });
  it("fails missing evidence and unsupported generated quantitative claims", () => { const x=base(); x.reportedEvidenceIds=[]; x.quantitativeClaims=[{claim:"50%",evidenceIds:[],generated:true}]; expect(validateFounderOsResult(x).failed.map(f=>f.code)).toEqual(expect.arrayContaining(["evidence_exists","claim_provenance"])); });
  it("hard-fails unauthorized external actions and active deterministic gates", () => { const x=base(); x.externalActions=[{type:"publish",executed:true}]; x.cannotCompleteIf=[{code:"pricing_source_missing",active:true}]; expect(validateFounderOsResult(x).hardFailure).toBe(true); });
});
