import {describe,expect,it} from "vitest";
import {automaticRepairEligibility,classifySeverity,compileProductLearning,futurePrimaryGoalInterfaces,maintainMvpReliabilityTemplate,mvpReliabilitySystem,observationFingerprint,PRIMARY_NEXT_GOALS} from "../services/mvp-reliability.js";
import {validateCommercialCommitmentTemplate} from "../services/commercial-validation.js";
describe("MVP reliability and product learning",()=>{
 it("is a parallel long-running system and corrects the commercial handoff",()=>{expect(mvpReliabilitySystem.id).toBe("mvp-reliability");expect(validateCommercialCommitmentTemplate.nextGoalHints).toEqual([...PRIMARY_NEXT_GOALS]);expect(validateCommercialCommitmentTemplate.nextGoalHints.some(x=>x.includes("delivery"))).toBe(false);expect(futurePrimaryGoalInterfaces["validate-retention"].measures).toContain("renewal")});
 it("deduplicates repeated errors while separating different failures",()=>{const a=observationFingerprint({type:"SERVER_ERROR",endpoint:"/api/signup",statusCode:500,summary:"boom abcdef1"}),repeat=observationFingerprint({type:"SERVER_ERROR",endpoint:"/api/signup",statusCode:500,summary:"boom 1234567"}),other=observationFingerprint({type:"BROKEN_ROUTE",endpoint:"/checkout",statusCode:404,summary:"missing"});expect(repeat).toBe(a);expect(other).not.toBe(a)});
 it("escalates unavailable and validation-blocking runtime failures",()=>{expect(classifySeverity({type:"DEPLOYMENT_FAILED"})).toBe("P0");expect(classifySeverity({type:"SERVER_ERROR",statusCode:500})).toBe("P1");expect(classifySeverity({type:"BROKEN_ROUTE",commerciallyBlocking:true})).toBe("P0")});
 it("admits only bounded reproducible repairs through the broker hook contract",()=>{expect(automaticRepairEligibility({type:"BROKEN_ROUTE",severity:"P1",reproducible:true,repositoryBound:true,writeScope:["src/routes/**"]}).eligible).toBe(true);expect(automaticRepairEligibility({type:"FUNCTIONAL_REGRESSION",severity:"P1",reproducible:true,repositoryBound:true,writeScope:[],highImpact:true}).eligible).toBe(false);expect(maintainMvpReliabilityTemplate.requiredCapabilities).toContain("github")});
 it("does not turn a speculative product request into an automatic feature",()=>{expect(automaticRepairEligibility({type:"PRODUCT_LEARNING",severity:"P3",reproducible:true,repositoryBound:true,writeScope:["src/**"],evidenceIds:["one-comment"]}).eligible).toBe(false);expect(automaticRepairEligibility({type:"PRODUCT_LEARNING",severity:"P2",reproducible:true,repositoryBound:true,writeScope:["src/**"],evidenceIds:["customer-1","opportunity-1"]}).eligible).toBe(true)});
 it("retains evidence, issue and verification in the learning ledger",()=>{const md=compileProductLearning([{observationId:"obs-1",summary:"Users abandon signup",evidenceIds:["analytics-1","customer-1"],severity:"P1",decision:"FIX",issueId:"issue-1",verification:{revision:"rev-c",healthy:true}}]);expect(md).toContain("analytics-1, customer-1");expect(md).toContain("issue-1");expect(md).toContain("rev-c")});
});
