import { describe, expect, it, vi } from "vitest";
import { PITCH_STEPS, bpwPitchResourcePack, compilePitch, compilePitchArtifacts, compilePitchTemplate, evaluatePitch, pitchFingerprint, pitchSystem, validatePitch, type PitchClaim, type PitchInput } from "../services/pitch.js";
const claim=(id:string, extra:Partial<PitchClaim>={}):PitchClaim=>({claimId:id,text:`Supported ${id}`,classification:"OBSERVED",evidenceIds:[`e-${id}`],sourceArtifactIds:["business-plan"],calculationIds:[],assumptionIds:[],contradictionIds:[],freshness:"CURRENT",confidence:"HIGH",maturity:"SUPPORTED",...extra});
const input=():PitchInput=>{const claims=PITCH_STEPS.map(s=>claim(s)),slides=PITCH_STEPS.map((step,i)=>({id:`slide-${i+1}`,step,title:step,purpose:step,headline:`Headline ${step}`,supportingPoints:["One point"],claimIds:[step],charts:[],visualDirection:"Evidence-led",speakerNotes:"Qualification",openQuestions:[]})); return {companyId:"c",goalId:"g",projectId:"p",deckId:"d",version:"1",sourceStateVersion:"firm:1",resourceVersion:"1.0.0",compiledAt:new Date("2026-09-18T00:00:00Z"),slides,claims,framework:{audience:{type:"BPW_JURY",decision:"advance",knowledgeLevel:"general",mainConcerns:["evidence"],requiredTopics:["business"],evidenceExpectations:["source-backed"],finalAsk:"advancement"},thesis:{pitchThesisId:"thesis-1",centralClaimId:"mission",problemClaimId:"problem",solutionClaimId:"solution",proofClaimIds:["metrics-validation"],businessLogicClaimIds:["business-model"],statusClaimIds:["status-future"],evidenceIds:["e-mission"],assumptionIds:[],contradictionIds:[],confidence:"HIGH"},beliefLadder:[{beliefId:"belief-1",statement:"Problem is real",slideIds:["slide-2"],claimIds:["problem"],evidenceIds:["e-problem"],contradictionIds:[],maturity:"SUPPORTED"}],archetype:"PROBLEM_FIRST",narrativeArc:[{phase:"CONTEXT",slideIds:["slide-1"]}],slidePurposes:slides.map((s)=>({slideId:s.id,audienceQuestion:s.step,primaryClaimId:s.step,supportingClaimIds:[],objectionIds:[],takeaway:s.step,recommendedVisual:"none",speakerNotePurpose:"qualify"})),objections:[{objectionId:"o-1",question:"Is it real?",affectedSlides:["slide-2"],evidenceIds:["e-problem"],resolutionStatus:"RESOLVED",remainingWeakness:"small sample",followupGoal:"validate-problem"}],ask:{askType:"BPW_ADVANCEMENT",whyNow:"evidence compiled",useOfResource:"next stage",milestoneUnlocked:"review",sourceIds:["e-status-future"],calculationIds:[]},delivery:{opening:"problem",closing:"ask",slideTimeBudgetSeconds:{"slide-1":30},keyEmphasis:["proof"],anticipatedQuestions:["traction"]}},knownEvidenceIds:claims.flatMap(c=>c.evidenceIds),knownCalculationIds:["calc-revenue"],knownAssumptionIds:["a-1"],knownCapabilityIds:["mvp"],knownTeamFactIds:["founder"],knownPartnerIds:[],canonicalMetrics:{revenue:1200},capitalRequirement:50000,staleDependencies:[],risks:[]};};
describe("BPW pitch compiler",()=>{
it("maps native Pitch Compilation, pitch-agent, canonical pack and dependency",()=>{expect(pitchSystem.title).toBe("Pitch Compilation");expect(compilePitchTemplate.recommendedOwnerRole).toBe("pitch-agent");expect(compilePitchTemplate.prerequisites).toEqual(["compile-business-plan accepted"]);expect(bpwPitchResourcePack.id).toBe("pitch.bpw-10-step");});
it("preserves canonical 10-step sequence including 3B and compiles readiness",()=>{const v=input(),d=compilePitch(v);expect(d.slides.map(s=>s.step)).toEqual([...PITCH_STEPS]);expect(d.overall.readiness).toBe("COMPILABLE");expect(validatePitch(v,d).pass).toBe(true);});
it("rejects wrong order, unresolved claims, and dense slides",()=>{const v=input();[v.slides[0],v.slides[1]]=[v.slides[1],v.slides[0]];v.slides[0].claimIds=["fake"];v.slides[0].supportingPoints=Array(6).fill("x");expect(validatePitch(v).failures).toEqual(expect.arrayContaining(["Slides do not follow the canonical BPW 10-step sequence","slide-2: unresolved claim fake","slide-2: exceeds five supporting points"]));});
it("rejects fake chart data and reconciles chart sources",()=>{const v=input();v.slides[5].charts=[{chartId:"market",chartType:"bar",metric:"SAM",dimensions:[],dataPoints:[{label:"SAM",value:800}],unit:"accounts",sourceIds:[],calculationIds:[]}];expect(validatePitch(v).failures).toContain("market: chart data lacks provenance");});
it("reconciles numbers and funding ask to canonical finance",()=>{const v=input();v.claims[7]={...v.claims[7],metricId:"revenue",numericValue:1300,calculationIds:["calc-revenue"]};v.askClaimId="status-future";v.claims[10]={...v.claims[10],numericValue:60000};expect(validatePitch(v).failures).toEqual(expect.arrayContaining(["business-model: numerical claim does not reconcile","Funding ask does not reconcile to capital requirement"]));});
it("rejects invented capability, team, partner and unauthorized social proof",()=>{const v=input();v.claims[2]={...v.claims[2],capabilityId:"roadmap",capabilityStatus:"CURRENT"};v.claims[9]={...v.claims[9],teamFactId:"advisor"};v.claims[0]={...v.claims[0],privateCustomer:true};expect(validatePitch(v).failures).toEqual(expect.arrayContaining(["solution: unregistered capability","team: unregistered team fact","mission: customer disclosure not authorized"]));});
it("keeps forecasts, hypotheses, contradictions and staleness explicit",()=>{const v=input();v.claims[3]={...v.claims[3],classification:"HYPOTHESIS",maturity:"HYPOTHESIS",evidenceIds:[],assumptionIds:["a-1"],freshness:"STALE",contradictionIds:["weak-moat"]};expect(compilePitch(v).overall.readiness).toBe("STALE");});
it("emits framework, objections, Q&A and truthful renderer status",()=>{const a=compilePitchArtifacts(input());expect(Object.keys(a)).toHaveLength(8);expect(a["business-case/pitch/READINESS.yaml"]).toContain("NOT_RENDERED");expect(a["business-case/pitch/PITCH_FRAMEWORK.yaml"]).toContain("beliefLadder");expect(a["business-case/pitch/Q_AND_A.md"]).toContain("Is it real?");});
it("validates belief, slide-purpose, thesis and framework funding ask",()=>{const v=input();v.framework.beliefLadder[0].claimIds=[];v.framework.slidePurposes[0].primaryClaimId="invented";v.framework.thesis.centralClaimId="invented";v.framework.ask={...v.framework.ask,askType:"FUNDING",amount:40000};expect(validatePitch(v).failures).toEqual(expect.arrayContaining(["belief-1: belief has no claims","Framework: unresolved primary claim invented","Pitch thesis central claim is unresolved","Framework funding ask does not reconcile to capital requirement"]));});
it("runs Firm before Hermes and blocks Hermes on deterministic failure",async()=>{const v=input(),d=compilePitch(v),order:string[]=[];await evaluatePitch(validatePitch(v,d),d,{firmBuild:async p=>{order.push(`firm-${p}`);return{success:true}},writeFirm:async()=>{order.push("write")},judge:async()=>{order.push("hermes");return{verdict:"ACCEPT"}}});expect(order).toEqual(["firm-before","write","firm-after","hermes"]);const judge=vi.fn();v.claims[0].evidenceIds=[];await evaluatePitch(validatePitch(v),compilePitch(v),{judge});expect(judge).not.toHaveBeenCalled();});
it("fingerprints unchanged input idempotently",()=>{expect(pitchFingerprint(input())).toBe(pitchFingerprint(input()));const v=input();v.sourceStateVersion="firm:2";expect(pitchFingerprint(v)).not.toBe(pitchFingerprint(input()));});});
