import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { analyzeUnitEconomicsTemplate, calculateUnitEconomics, compileEconomicReports, economicDecision, evaluateEconomicSufficiency, runScenario, sensitivityAnalysis, unitEconomicsSystem, validateEconomicInput, type EconomicInput, type EconomicModelContract, type FinancialAssumption } from "../services/unit-economics.js";
const fixtures = JSON.parse(readFileSync(new URL("./fixtures/unit-economics/scenarios.json", import.meta.url), "utf8"));
const contract: EconomicModelContract = { modelId: "model-1", version: 1, unit: "ACCOUNT", revenueModel: "SERVICE", currency: "USD", period: "2026-Q3", variableCostDefinition: ["COMPUTE", "SUPPORT"], fixedCostDefinition: ["BASE_INFRASTRUCTURE"], sourceIds: ["retention-1", "pricing-1"] };
const input = (inputId: string, category: EconomicInput["category"], value: number | null, extra: Partial<EconomicInput> = {}): EconomicInput => ({ inputId, name: inputId, value, unit: "minor_currency_unit", currency: "USD", period: contract.period, scope: "cohort:q3", sourceIds: [`source:${inputId}`], classification: "MEASURED", confidence: "HIGH", category, ...extra });
const complete = [input("payment", "REVENUE_RECEIVED", 10000, { accountRef: "a1" }), input("refund", "REFUND", 1000, { accountRef: "a1" }), input("compute", "VARIABLE_COST", 2000, { costType: "COMPUTE" }), input("support", "VARIABLE_COST", 3000, { costType: "SUPPORT" })];

describe("unit economics and financial case", () => {
  it("maps the native Project and Goal after retention to the BMC handoff", () => { expect(unitEconomicsSystem.title).toBe("Unit Economics & Financial Case"); expect(unitEconomicsSystem.goals).toEqual(["analyze-unit-economics"]); expect(analyzeUnitEconomicsTemplate.prerequisites).toEqual(["validate-retention accepted"]); expect(analyzeUnitEconomicsTemplate.nextGoalHints).toEqual(["compile-business-model-canvas"]); });
  it("requires an explicit economic unit, revenue model, and classified sourced inputs", () => { expect(contract.unit).toBe("ACCOUNT"); expect(validateEconomicInput(input("revenue", "REVENUE_RECEIVED", 100), contract).pass).toBe(true); expect(validateEconomicInput(input("guess", "OTHER", 100, { classification: "ESTIMATED", sourceIds: [] }), contract).pass).toBe(false); expect(validateEconomicInput(input("synthetic", "OTHER", 100, { synthetic: true }), contract).pass).toBe(false); });
  it("rejects mixed currencies, unresolved assumptions, and calculated values without formulas", () => { expect(validateEconomicInput(input("eur", "OTHER", 100, { currency: "EUR" }), contract).pass).toBe(false); expect(validateEconomicInput(input("calc", "OTHER", 100, { classification: "CALCULATED" }), contract).pass).toBe(false); expect(validateEconomicInput(input("assumed", "OTHER", 100, { classification: "ASSUMPTION", sourceIds: [] }), contract).pass).toBe(false); });
  it("calculates net received revenue, complete direct costs, contribution, and gross margin", () => { const result = calculateUnitEconomics(contract, complete); expect(result).toMatchObject({ netRevenue: 9000, directCostsComplete: true, contribution: 4000, grossMargin: 4000 / 9000 }); expect(result.costDefinition).toEqual(["COMPUTE", "SUPPORT"]); });
  it("propagates missing compute cost instead of silently assuming zero", () => { const result = calculateUnitEconomics(contract, complete.filter((item) => item.costType !== "COMPUTE")); expect(result).toMatchObject({ directCostsComplete: false, contribution: null, grossMargin: null, grossMarginStatus: "PARTIAL" }); expect(result.unknowns).toContain("variable cost:COMPUTE"); });
  it("separates variable and fixed cost and calculates break-even only from positive contribution", () => { const result = calculateUnitEconomics(contract, [...complete, input("overhead", "FIXED_COST", 10000)]); expect(result.variableCosts).toHaveLength(2); expect(result.fixedCosts).toBe(10000); expect(result.breakEvenUnits).toBe(3); });
  it("calculates CAC and channel CAC only with real acquired-customer denominators", () => { const known = calculateUnitEconomics(contract, [...complete, input("sales", "ACQUISITION_COST", 5000, { channel: "founder_outreach" }), input("new-customers", "ACQUIRED_CUSTOMERS", 10), input("new-outreach", "ACQUIRED_CUSTOMERS", 5, { channel: "founder_outreach", unit: "customers", currency: undefined })]); expect(known.cac).toBe(500); expect(known.cacByChannel.founder_outreach).toBe(1000); const unknown = calculateUnitEconomics(contract, [...complete, input("sales", "ACQUISITION_COST", 5000)]); expect(unknown.cac).toBeNull(); });
  it("separates observed LTV-to-date from explicitly modeled LTV", () => { const observed = calculateUnitEconomics(contract, complete); expect(observed.observedLtvToDate).toBe(9000); expect(observed.modeledLtv).toBeNull(); const modeled = calculateUnitEconomics(contract, [...complete, input("MODELED_LTV", "OTHER", 15000, { name: "MODELED_LTV", classification: "CALCULATED", formula: "periodic contribution * assumed periods", sourceIds: ["assumption:retention-periods"] })]); expect(modeled.observedLtvToDate).toBe(9000); expect(modeled.modeledLtv).toBe(15000); });
  it("gates payback on both CAC and periodic contribution", () => { const known = calculateUnitEconomics(contract, [...complete, input("sales", "ACQUISITION_COST", 5000), input("customers", "ACQUIRED_CUSTOMERS", 10, { unit: "customers", currency: undefined }), input("periodic", "PERIODIC_CONTRIBUTION", 250)]); expect(known.paybackPeriods).toBe(2); expect(calculateUnitEconomics(contract, [...complete, input("periodic", "PERIODIC_CONTRIBUTION", 250)]).paybackPeriods).toBeNull(); });
  it("does not invent cash, burn, or runway", () => { const result = calculateUnitEconomics(contract, complete); expect(result.runwayPeriods).toBeNull(); expect(result.unknowns).toContain("runway"); });
  it("runs sourced scenarios deterministically and rejects arbitrary out-of-range values", () => { const assumption: FinancialAssumption = { assumptionId: "support-range", statement: "Support cost range", range: { min: 2000, max: 5000 }, unit: "USD cents", reason: "Observed pilot range", sourceIds: ["timesheet-1"], confidence: "MEDIUM", sensitivity: "HIGH", status: "OPEN", owner: "finance", validationNeeded: "More accounts" }; const valid = runScenario(contract, complete, [assumption], { scenarioId: "conservative", name: "CONSERVATIVE", changes: [{ inputId: "support", value: 5000, reason: "Upper observed range", sourceIds: [], assumptionId: "support-range" }] }); expect(valid.pass).toBe(true); expect(valid.outputs.contribution).toBe(2000); const rejected = runScenario(contract, complete, [assumption], { scenarioId: "invented", name: "UPSIDE", changes: [{ inputId: "support", value: 1, reason: "wishful", sourceIds: [], assumptionId: "support-range" }] }); expect(rejected.pass).toBe(false); });
  it("identifies the dominant explicit assumption through deterministic sensitivity", () => { const assumptions: FinancialAssumption[] = [{ assumptionId: "compute-range", statement: "Compute range", range: { min: 1000, max: 6000 }, unit: "cents", reason: "usage range", sourceIds: ["meter"], confidence: "MEDIUM", sensitivity: "HIGH", status: "OPEN", owner: "finance", validationNeeded: "meter more" }, { assumptionId: "support-range", statement: "Support range", range: { min: 2500, max: 3500 }, unit: "cents", reason: "time range", sourceIds: ["time"], confidence: "MEDIUM", sensitivity: "MEDIUM", status: "OPEN", owner: "finance", validationNeeded: "time more" }]; const inputs = complete.map((item) => item.inputId === "compute" ? { ...item, classification: "ASSUMPTION" as const, sourceIds: ["assumption:compute-range"] } : item.inputId === "support" ? { ...item, classification: "ASSUMPTION" as const, sourceIds: ["assumption:support-range"] } : item); expect(sensitivityAnalysis(contract, inputs, assumptions).dominantAssumptionId).toBe("compute-range"); });
  it("uses structured viability decisions without claiming guaranteed profit or PMF", () => { expect(economicDecision(calculateUnitEconomics(contract, complete.filter((item) => item.category !== "REVENUE_RECEIVED")))).toBe("GATHER_MORE_REVENUE_DATA"); expect(economicDecision(calculateUnitEconomics(contract, complete.filter((item) => item.costType !== "COMPUTE")))).toBe("GATHER_MORE_COST_DATA"); expect(JSON.stringify(economicDecision(calculateUnitEconomics(contract, complete)))).not.toMatch(/GUARANTEED|PRODUCT_MARKET_FIT/); });
  it("blocks Firm and Hermes when deterministic financial evidence fails", async () => { const firmBuild = vi.fn(), judge = vi.fn(); const result = await evaluateEconomicSufficiency({ pass: false, hardFailure: true, failures: ["unsupported denominator"] }, [], { firmBuild, judge }); expect(result.accepted).toBe(false); expect(firmBuild).not.toHaveBeenCalled(); expect(judge).not.toHaveBeenCalled(); });
  it("builds Firm before and after and only then asks Hermes for business meaning", async () => { const order: string[] = []; const result = await evaluateEconomicSufficiency({ pass: true, hardFailure: false, failures: [] }, [{ type: "metric", id: "contribution" }], { firmBuild: async (phase) => { order.push(`firm-${phase}`); return { success: true }; }, writeFirm: async () => { order.push("firm-write"); }, judge: async () => { order.push("hermes"); return { verdict: "ACCEPT" }; } }); expect(result.accepted).toBe(true); expect(order).toEqual(["firm-before", "firm-write", "firm-after", "hermes"]); });
  it("compiles machine-readable and narrative evidence-linked reports with explicit unknowns", () => { const compiled = compileEconomicReports(contract, complete, [], []); expect(Object.keys(compiled.artifacts)).toEqual(expect.arrayContaining(["business-case/UNIT_ECONOMICS.md", "business-case/UNIT_ECONOMICS.yaml", "business-case/FINANCIAL_CASE.md", "business-case/FINANCIAL_ASSUMPTIONS.yaml", "business-case/SCENARIOS.yaml"])); expect(compiled.artifacts["business-case/UNIT_ECONOMICS.yaml"]).toContain("payback: null"); expect(compiled.artifacts["business-case/FINANCIAL_CASE.md"]).toContain("evidence:"); });
  it("contains required scenarios A-L", () => { expect(fixtures.map((scenario: { id: string }) => scenario.id)).toEqual(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]); });
});
