import { createHash } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import type { Db } from "@paperclipai/db";
import { activityLog, artifactStaleness, businessModelCanvases } from "@paperclipai/db";
import { founderosContentService, type GoalTemplate, type ResourcePackDefinition, type SystemDefinition } from "./founderos-content/index.js";

export const BMC_BLOCKS = ["customerSegments", "valuePropositions", "channels", "customerRelationships", "revenueStreams", "keyResources", "keyActivities", "keyPartners", "costStructure"] as const;
export type BmcBlock = typeof BMC_BLOCKS[number];
export const BMC_ENTRY_STATUSES = ["VALIDATED", "SUPPORTED", "EARLY_EVIDENCE", "HYPOTHESIS", "ASSUMPTION", "UNKNOWN", "CONTRADICTED"] as const;
export const BMC_CONFIDENCE = ["LOW", "MEDIUM", "HIGH"] as const;
export const BUSINESS_MODEL_DECISIONS = ["BUSINESS_MODEL_COHERENT", "BUSINESS_MODEL_PARTIALLY_SUPPORTED", "VALIDATE_CHANNEL", "VALIDATE_REVENUE_MODEL", "REDUCE_COST_STRUCTURE_RISK", "REFINE_SEGMENT", "REFINE_VALUE_PROPOSITION", "GATHER_MORE_RETENTION_DATA", "BUSINESS_MODEL_NOT_SUPPORTED"] as const;

export const businessModelSystem: SystemDefinition = { id: "business-model", version: "1.0.0", title: "Business Model Synthesis", purpose: "Compile the current evidence-backed company state into a provenance-preserving nine-block Business Model Canvas.", stateDependencies: ["analyzed unit economics", "validated customer value and retention"], goals: ["compile-business-model-canvas"], expectedOutputs: ["business-case/BUSINESS_MODEL_CANVAS.md", "business-case/BUSINESS_MODEL_CANVAS.yaml", "business-case/BUSINESS_MODEL_RISKS.md"], wakeConditions: ["unit_economics_updated", "pricing_updated", "ICP_updated", "offer_updated", "value_updated", "retention_updated", "channel_evidence_updated", "operator_resumed"], evidenceFeedbackLoop: ["canonical company state -> block compilation -> deterministic integrity -> Hermes coherence judgment"], stopConditions: ["structured business-model decision", "operator stop"] };
export const compileBusinessModelCanvasTemplate: GoalTemplate = { id: "compile-business-model-canvas", version: "1.0.0", system: "business-model", title: "Compile Business Model Canvas", objective: "Compile a concise nine-block business model from current canonical evidence without filling unknown blocks with invented prose.", recommendedOwnerRole: "business model architect", requiredSkills: ["business-model-canvas-design", "jobs-to-be-done", "value-proposition-design", "bpw-business-model-canvas", "bpw-evidence-and-source-discipline"], supportPacks: [{ id: "bmc.standard", version: "1.0.0", required: true }, { id: "bpw.bmc", version: "1.0.0", required: true }], requiredCapabilities: ["firm"], inputPaths: ["firm/**", "evidence/**", "business-case/CUSTOMER_PROBLEM_REPORT.md", "business-case/ICP.md", "business-case/SEGMENT_MAP.md", "business-case/MARKET_ANALYSIS.md", "business-case/OFFER.md", "business-case/VALUE_PROPOSITION.md", "business-case/UNIT_ECONOMICS.*", "business-case/FINANCIAL_CASE.md", "sales/**", "product/**"], outputPaths: businessModelSystem.expectedOutputs, acceptanceCriteria: ["All nine blocks exist structurally", "Every material entry retains evidence, assumption, contradiction, source artifact, status and deterministic confidence", "Revenue and cost agree with commercial and economic state", "Unknowns remain explicit", "Firm builds before and after", "Hermes runs only after deterministic integrity"], cannotCompleteIf: ["Unsupported prose is presented as validated", "Synthetic evidence validates a block", "Revenue or cost contradicts authoritative state", "Unresolved segment, offer, evidence, or assumption references", "BMC is cited as primary evidence"], writeScope: ["business-case/BUSINESS_MODEL_CANVAS.*", "business-case/BUSINESS_MODEL_RISKS.md", "firm/**"], externalActionPolicy: "NO_EXTERNAL_ACTION", wakeConditions: businessModelSystem.wakeConditions, nextGoalHints: ["compile-bpw-financial-plan"], prerequisites: ["analyze-unit-economics accepted"], evidenceRequirements: ["problem and ICP evidence", "offer/value evidence", "commercial and channel evidence", "usage/value/retention evidence", "unit economics and financial case"], firm: { required: true, buildBefore: true, buildAfter: true } };
export const bmcResourcePacks: ResourcePackDefinition[] = [{ id: "bmc.standard", version: "1.0.0", tier: "GOAL_SPECIFIC", path: "resources/business-model/bmc", requiredSkills: ["business-model-canvas-design", "bpw-evidence-and-source-discipline"], requiredCapabilities: ["firm"], installedFiles: ["RESOURCE.md", "manifest.yaml", "canvas-contract.yaml", "block-guidance.md", "evidence-map.md", "layout.md", "quality-gate.md"], qualityGates: ["nine-block-structure", "entry-provenance", "financial-reconciliation", "unknown-preservation"], dependencies: [], compatibility: "Compatible with canonical bpw-business-model-canvas; BPW source must remain pinned by the content registry." }, { id: "bpw.bmc", version: "1.0.0", tier: "GOAL_SPECIFIC", path: "resources/business-model/bmc", requiredSkills: ["bpw-business-model-canvas"], requiredCapabilities: ["firm"], installedFiles: ["RESOURCE.md", "manifest.yaml", "canvas-contract.yaml", "evidence-map.md", "quality-gate.md"], qualityGates: ["bpw-bmc-methodology"], dependencies: ["bmc.standard"], compatibility: "Canonical identifier retained when the external BPW content source is unavailable." }];

export interface BmcEntryInput { statement: string; evidenceIds: string[]; assumptionIds: string[]; contradictionIds: string[]; sourceArtifacts: string[]; sourceKinds?: string[]; segmentId?: string; offerId?: string; role?: "USER" | "BUYER" | "DECISION_MAKER" | "BENEFICIARY"; channelType?: "DISCOVERY" | "ACQUISITION" | "SALES" | "DELIVERY" | "SUPPORT" | "RETENTION"; revenueState?: "HYPOTHESIZED" | "QUOTED" | "CONTRACTED" | "INVOICED" | "RECEIVED" | "REFUNDED"; relationshipStatus?: string; resourceStatus?: "CURRENT" | "REQUIRED" | "HYPOTHESIZED"; partnerStatus?: "ACTUAL" | "DEPENDENCY" | "PROPOSED" | "HYPOTHESIZED"; classification?: string; synthetic?: boolean; stale?: boolean; requestedStatus?: typeof BMC_ENTRY_STATUSES[number] }
export interface BmcCompileInput { companyId: string; canvasId: string; version: string; sourceStateVersion: string; goalId: string; projectId: string; blocks: Record<BmcBlock, BmcEntryInput[]>; openQuestions: string[]; staleDependencies: string[]; knownEvidenceIds: string[]; knownAssumptionIds: string[]; knownContradictionIds: string[]; knownSegmentIds: string[]; knownOfferIds: string[]; verifiedReceivedRevenueEvidenceIds: string[]; economicCostEvidenceIds: string[]; compiledAt: Date }
export interface BmcEntry extends BmcEntryInput { status: typeof BMC_ENTRY_STATUSES[number]; confidence: typeof BMC_CONFIDENCE[number] }

export function deriveEntryStatus(entry: BmcEntryInput) {
  if (entry.contradictionIds.length) return "CONTRADICTED" as const;
  if (!entry.evidenceIds.length && !entry.assumptionIds.length) return "UNKNOWN" as const;
  if (!entry.evidenceIds.length && entry.assumptionIds.length) return "ASSUMPTION" as const;
  const diversity = new Set(entry.sourceKinds ?? entry.sourceArtifacts).size;
  if (entry.evidenceIds.length >= 3 && diversity >= 2 && !entry.stale) return "VALIDATED" as const;
  if (entry.evidenceIds.length >= 2 && !entry.stale) return "SUPPORTED" as const;
  return entry.requestedStatus === "HYPOTHESIS" ? "HYPOTHESIS" as const : "EARLY_EVIDENCE" as const;
}
export function deriveEntryConfidence(entry: BmcEntryInput, status = deriveEntryStatus(entry)) {
  if (status === "UNKNOWN" || status === "ASSUMPTION" || status === "CONTRADICTED" || entry.synthetic) return "LOW" as const;
  const diversity = new Set(entry.sourceKinds ?? entry.sourceArtifacts).size;
  if (status === "VALIDATED" && diversity >= 2 && !entry.stale) return "HIGH" as const;
  return entry.stale ? "LOW" as const : "MEDIUM" as const;
}
export function compileCanvas(input: BmcCompileInput) {
  const blocks = Object.fromEntries(BMC_BLOCKS.map((block) => [block, { entries: (input.blocks[block] ?? []).map((entry) => ({ ...entry, status: deriveEntryStatus(entry), confidence: deriveEntryConfidence(entry) })) }])) as Record<BmcBlock, { entries: BmcEntry[] }>;
  const entries = BMC_BLOCKS.flatMap((block) => blocks[block].entries), evidenceBacked = entries.filter((entry) => entry.evidenceIds.length && !entry.synthetic), material = entries.filter((entry) => entry.status !== "UNKNOWN");
  return { canvas: { version: input.version, compiledAt: input.compiledAt.toISOString(), companyId: input.companyId, sourceStateVersion: input.sourceStateVersion }, blocks, openQuestions: input.openQuestions, staleDependencies: input.staleDependencies, overallEvidenceCoverage: material.length ? evidenceBacked.length / material.length : 0 };
}
export function validateCanvas(input: BmcCompileInput, canvas = compileCanvas(input)) {
  const failures: string[] = [], knownEvidence = new Set(input.knownEvidenceIds), knownAssumptions = new Set(input.knownAssumptionIds), knownContradictions = new Set(input.knownContradictionIds), knownSegments = new Set(input.knownSegmentIds), knownOffers = new Set(input.knownOfferIds), received = new Set(input.verifiedReceivedRevenueEvidenceIds), costs = new Set(input.economicCostEvidenceIds);
  for (const block of BMC_BLOCKS) { if (!canvas.blocks[block]) failures.push(`Missing BMC block ${block}`); for (const entry of canvas.blocks[block]?.entries ?? []) { if (entry.synthetic && ["VALIDATED", "SUPPORTED", "EARLY_EVIDENCE"].includes(entry.status)) failures.push(`${block}: synthetic evidence cannot validate an entry`); for (const id of entry.evidenceIds) if (!knownEvidence.has(id)) failures.push(`${block}: unresolved evidence ${id}`); for (const id of entry.assumptionIds) if (!knownAssumptions.has(id)) failures.push(`${block}: unresolved assumption ${id}`); for (const id of entry.contradictionIds) if (!knownContradictions.has(id)) failures.push(`${block}: unresolved contradiction ${id}`); if (entry.status !== "UNKNOWN" && !entry.evidenceIds.length && !entry.assumptionIds.length) failures.push(`${block}: unsupported material statement`); if (entry.segmentId && !knownSegments.has(entry.segmentId)) failures.push(`${block}: unresolved segment ${entry.segmentId}`); if (entry.offerId && !knownOffers.has(entry.offerId)) failures.push(`${block}: unresolved offer ${entry.offerId}`); if (block === "valuePropositions" && !entry.evidenceIds.length) failures.push(`${block}: value proposition lacks problem/value evidence`); if (block === "revenueStreams" && entry.revenueState === "RECEIVED" && !entry.evidenceIds.some((id) => received.has(id))) failures.push(`${block}: received revenue does not reconcile to verified payment evidence`); if (block === "costStructure" && entry.status !== "UNKNOWN" && !entry.evidenceIds.some((id) => costs.has(id))) failures.push(`${block}: cost does not reconcile to unit-economics evidence`); if (block === "keyPartners" && entry.partnerStatus === "ACTUAL" && !entry.evidenceIds.length) failures.push(`${block}: actual partner requires evidence`); } }
  return { pass: !failures.length, hardFailure: failures.length > 0, failures };
}
export function compileBusinessModelRisks(canvas: ReturnType<typeof compileCanvas>) {
  const risks: Array<{ riskId: string; block: BmcBlock; statement: string; evidenceIds: string[]; assumptionIds: string[]; recommendation: string }> = [];
  const recommendation: Record<BmcBlock, string> = { customerSegments: "refine-icp", valuePropositions: "validate-value-realization", channels: "validate-demand", customerRelationships: "validate-retention", revenueStreams: "validate-commercial-commitment", keyResources: "compile-business-model-canvas", keyActivities: "compile-business-model-canvas", keyPartners: "compile-business-model-canvas", costStructure: "analyze-unit-economics" };
  for (const block of BMC_BLOCKS) { const entries = canvas.blocks[block].entries, weak = !entries.length || entries.every((entry) => ["UNKNOWN", "ASSUMPTION", "HYPOTHESIS", "CONTRADICTED"].includes(entry.status)); if (weak) risks.push({ riskId: `risk-${block}`, block, statement: `${block} is unsupported, assumed, unknown, or contradicted`, evidenceIds: entries.flatMap((entry) => entry.evidenceIds), assumptionIds: entries.flatMap((entry) => entry.assumptionIds), recommendation: recommendation[block] }); }
  return risks;
}
export function businessModelDecision(canvas: ReturnType<typeof compileCanvas>, risks = compileBusinessModelRisks(canvas)) { const weak = new Set(risks.map((risk) => risk.block)); if (weak.has("customerSegments")) return "REFINE_SEGMENT"; if (weak.has("valuePropositions")) return "REFINE_VALUE_PROPOSITION"; if (weak.has("revenueStreams")) return "VALIDATE_REVENUE_MODEL"; if (weak.has("costStructure")) return "REDUCE_COST_STRUCTURE_RISK"; if (weak.has("channels")) return "VALIDATE_CHANNEL"; if (risks.length) return "BUSINESS_MODEL_PARTIALLY_SUPPORTED"; return canvas.overallEvidenceCoverage >= 0.8 ? "BUSINESS_MODEL_COHERENT" : "BUSINESS_MODEL_PARTIALLY_SUPPORTED"; }
function yaml(value: unknown, indent = 0): string { if (value === null) return "null"; if (Array.isArray(value)) return value.length ? value.map((item) => `${" ".repeat(indent)}- ${typeof item === "object" ? `\n${yaml(item, indent + 2)}` : String(item)}`).join("\n") : "[]"; if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([key, item]) => `${" ".repeat(indent)}${key}: ${typeof item === "object" && item !== null ? `\n${yaml(item, indent + 2)}` : String(item)}`).join("\n"); return String(value); }
export function compileCanvasArtifacts(canvas: ReturnType<typeof compileCanvas>, risks = compileBusinessModelRisks(canvas), decision = businessModelDecision(canvas, risks)) {
  const md = ["# Business Model Canvas", `Source state: ${canvas.canvas.sourceStateVersion}`, `Evidence coverage: ${canvas.overallEvidenceCoverage}`, ...BMC_BLOCKS.flatMap((block) => [`## ${block.replace(/([A-Z])/g, " $1")}`, ...(canvas.blocks[block].entries.length ? canvas.blocks[block].entries.map((entry) => `- ${entry.statement} — ${entry.status}/${entry.confidence}; evidence ${entry.evidenceIds.join(", ") || "UNKNOWN"}; assumptions ${entry.assumptionIds.join(", ") || "NONE"}; contradictions ${entry.contradictionIds.join(", ") || "NONE"}`) : ["- UNKNOWN — no supported current entry"]), ""]), "## Open questions", ...canvas.openQuestions.map((question) => `- ${question}`), "## Decision", decision].join("\n");
  const riskMd = ["# Business Model Risks", ...risks.map((risk) => `- ${risk.riskId} [${risk.block}]: ${risk.statement}; evidence ${risk.evidenceIds.join(", ") || "UNKNOWN"}; assumptions ${risk.assumptionIds.join(", ") || "NONE"}; next Goal ${risk.recommendation}`)].join("\n");
  return { "business-case/BUSINESS_MODEL_CANVAS.yaml": yaml(canvas), "business-case/BUSINESS_MODEL_CANVAS.md": md, "business-case/BUSINESS_MODEL_RISKS.md": riskMd };
}
export function canvasFingerprint(input: BmcCompileInput) { const stable = { sourceStateVersion: input.sourceStateVersion, blocks: input.blocks, openQuestions: input.openQuestions, staleDependencies: input.staleDependencies, evidence: input.knownEvidenceIds.slice().sort(), assumptions: input.knownAssumptionIds.slice().sort() }; return createHash("sha256").update(JSON.stringify(stable)).digest("hex"); }

interface BmcHooks { firmBuild?(phase: "before" | "after"): Promise<{ success: boolean }>; writeFirm?(records: unknown[]): Promise<void>; writeArtifacts?(artifacts: Record<string, string>): Promise<void>; registerWorkProducts?(input: { companyId: string; goalId: string; projectId: string; artifacts: Record<string, string> }): Promise<void>; judge?(validation: { pass: boolean; hardFailure: boolean; failures: string[] }, canvas: ReturnType<typeof compileCanvas>, risks: ReturnType<typeof compileBusinessModelRisks>): Promise<{ verdict: string; decision?: string; weakestBlock?: string }> }
export async function evaluateCanvas(validation: { pass: boolean; hardFailure: boolean; failures: string[] }, canvas: ReturnType<typeof compileCanvas>, risks: ReturnType<typeof compileBusinessModelRisks>, hooks: BmcHooks) { if (!validation.pass || validation.hardFailure) return { accepted: false, judgment: null }; if (hooks.firmBuild && !(await hooks.firmBuild("before")).success) throw new Error("Firm build before BMC failed"); await hooks.writeFirm?.(BMC_BLOCKS.flatMap((block) => canvas.blocks[block].entries.map((entry, index) => ({ type: block === "customerSegments" ? "customer_segment" : block === "valuePropositions" ? "value_proposition" : block === "channels" ? "channel" : "claim", id: `bmc:${block}:${index}`, statement: entry.statement, status: entry.status, evidenceIds: entry.evidenceIds, assumptionIds: entry.assumptionIds })))); if (hooks.firmBuild && !(await hooks.firmBuild("after")).success) throw new Error("Firm build after BMC failed"); const judgment = await hooks.judge?.(validation, canvas, risks); return { accepted: judgment?.verdict === "ACCEPT", judgment: judgment ?? null }; }
export function businessModelCanvasService(db: Db, hooks: BmcHooks = {}) { const content = founderosContentService(db); const activity = (companyId: string, action: string, entityId: string, details: Record<string, unknown>) => db.insert(activityLog).values({ companyId, actorType: "system", actorId: "business-model", action, entityType: "business_model_canvas", entityId, details });
  async function activate(input: { companyId: string; parentGoalId: string; sourceRepository: string; sourceCommit: string }) { const source = { repository: input.sourceRepository, commit: input.sourceCommit }, goal = await content.instantiateGoal(input.companyId, source, compileBusinessModelCanvasTemplate, input.parentGoalId), project = await content.activateSystem(input.companyId, source, businessModelSystem, goal.goal.id, goal.goal.ownerAgentId!); const titles = ["Compile segments", "Compile value proposition", "Compile channels/relationships", "Compile revenue/cost model", "Compile resources/activities/partners", "Validate coherence", "Review business-model risks"], issues = []; for (const title of titles) issues.push((await content.createGoalIssue(input.companyId, goal.goal.id, project.project.id, goal.goal.ownerAgentId!, title)).issue); return { goal: goal.goal, project: project.project, issues }; }
  async function compile(input: BmcCompileInput) { const fingerprint = canvasFingerprint(input), existing = await db.select().from(businessModelCanvases).where(and(eq(businessModelCanvases.companyId, input.companyId), eq(businessModelCanvases.sourceFingerprint, fingerprint))).limit(1).then((rows) => rows[0]); if (existing) return { canvas: existing, reused: true }; const canvas = compileCanvas(input), validation = validateCanvas(input, canvas), risks = compileBusinessModelRisks(canvas), decision = businessModelDecision(canvas, risks), artifacts = compileCanvasArtifacts(canvas, risks, decision); const evaluation = await evaluateCanvas(validation, canvas, risks, hooks); if (!validation.pass) return { validation, canvas, risks, decision: "BUSINESS_MODEL_NOT_SUPPORTED" as const, artifacts, judgment: null, reused: false }; await hooks.writeArtifacts?.(artifacts); await hooks.registerWorkProducts?.({ companyId: input.companyId, goalId: input.goalId, projectId: input.projectId, artifacts }); const [row] = await db.insert(businessModelCanvases).values({ companyId: input.companyId, goalId: input.goalId, projectId: input.projectId, canvasId: input.canvasId, version: input.version, sourceStateVersion: input.sourceStateVersion, sourceFingerprint: fingerprint, blocks: canvas.blocks, openQuestions: input.openQuestions, staleDependencies: input.staleDependencies, overallEvidenceCoverage: String(canvas.overallEvidenceCoverage), decision, status: input.staleDependencies.length ? "STALE_AT_COMPILE" : "CURRENT", compiledAt: input.compiledAt }).returning(); for (const artifact of ["financial-planning", "business-plan", "pitch", "kickstarter-economics", "content-value-claims"]) await db.insert(artifactStaleness).values({ companyId: input.companyId, artifact, reason: "Business Model Canvas changed", evidenceId: row.canvasId, affectedDependency: "business-model-canvas" }).onConflictDoNothing(); await activity(input.companyId, "business_model.canvas_compiled", row.id, { decision, coverage: canvas.overallEvidenceCoverage, riskCount: risks.length }); return { canvas: row, compiled: canvas, validation, risks, decision, artifacts, judgment: evaluation.judgment, nextGoal: decision === "BUSINESS_MODEL_COHERENT" ? "compile-bpw-financial-plan" : risks[0]?.recommendation ?? null, reused: false }; }
  async function unresolvedStaleness(companyId: string) { return db.select().from(artifactStaleness).where(and(eq(artifactStaleness.companyId, companyId), eq(artifactStaleness.artifact, "BMC"), isNull(artifactStaleness.resolvedAt))); }
  return { activate, compile, unresolvedStaleness }; }
