import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import type { Db } from "@paperclipai/db";
import { activityLog, artifactStaleness, businessPlans } from "@paperclipai/db";
import { founderosContentService, type GoalTemplate, type ResourcePackDefinition, type SystemDefinition } from "./founderos-content/index.js";

export const BUSINESS_PLAN_CHAPTERS = ["executive-summary", "product-service", "founding-team", "market-analysis", "marketing-go-to-market", "company-organisation", "financial-planning", "sustainability"] as const;
export type BusinessPlanChapterId = typeof BUSINESS_PLAN_CHAPTERS[number];
export const STATEMENT_TYPES = ["OBSERVED_FACT", "EXTERNAL_SOURCE", "CUSTOMER_EVIDENCE", "COMMERCIAL_EVIDENCE", "PRODUCT_BEHAVIOR", "CALCULATED", "FORECAST", "FOUNDER_ASSUMPTION", "HYPOTHESIS", "UNKNOWN"] as const;
export const CHAPTER_READINESS = ["SUPPORTED", "PARTIALLY_SUPPORTED", "ASSUMPTION_HEAVY", "BLOCKED", "STALE"] as const;

export const businessPlanSystem: SystemDefinition = { id: "bpw-business-plan", version: "1.0.0", title: "Business Plan Compilation", purpose: "Compile an evidence-backed BPW-compatible business plan without turning narrative into evidence.", stateDependencies: ["accepted BPW financial plan", "current business model canvas"], goals: ["compile-business-plan"], expectedOutputs: ["business-case/business-plan/BUSINESS_PLAN.yaml", "business-case/business-plan/BUSINESS_PLAN.md", "business-case/business-plan/CLAIM_EVIDENCE_MAP.yaml", "business-case/business-plan/SOURCES.yaml", "business-case/business-plan/BUSINESS_PLAN_RISKS.md", "business-case/business-plan/READINESS.yaml"], wakeConditions: ["financial_plan_updated", "business_model_updated", "market_updated", "team_updated", "product_capability_updated", "operator_resumed"], evidenceFeedbackLoop: ["canonical state -> deterministic chapter assembly -> constrained editing -> fact preservation -> Hermes"], stopConditions: ["structured plan decision", "operator stop"] };
export const compileBusinessPlanTemplate: GoalTemplate = { id: "compile-business-plan", version: "1.0.0", system: businessPlanSystem.id, title: "Compile Business Plan", objective: "Assemble a coherent BPW business plan whose material claims remain classified, traceable, current, and financially consistent.", recommendedOwnerRole: "business plan editor", requiredSkills: ["bpw-business-plan", "bpw-evidence-and-source-discipline", "bpw-market-analysis", "bpw-market-segmentation", "bpw-business-model-canvas", "bpw-financial-planning", "bpw-sustainability"], supportPacks: [{ id: "bpw.business-plan", version: "1.0.0", required: true }], requiredCapabilities: ["firm"], inputPaths: ["firm/**", "evidence/**", "sales/**", "product/**", "business-case/BUSINESS_MODEL_CANVAS.yaml", "business-case/financial-plan/**"], outputPaths: businessPlanSystem.expectedOutputs, acceptanceCriteria: ["Material statements resolve to evidence, calculations, or explicit assumptions", "Financial and market claims reconcile exactly", "Executive Summary is derived after substantive chapters", "Unknowns, contradictions, privacy, and staleness are preserved", "Firm builds before and after deterministic validation"], cannotCompleteIf: ["Narrative invents a fact", "Financial prose disagrees with the canonical model", "Private customer data is exposed", "Hermes repairs deterministic failures"], writeScope: ["business-case/business-plan/**", "firm/**"], externalActionPolicy: "NO_EXTERNAL_ACTION", wakeConditions: businessPlanSystem.wakeConditions, nextGoalHints: ["compile-pitch"], prerequisites: ["compile-bpw-financial-plan accepted"], evidenceRequirements: ["validated company evidence chain", "business model canvas", "canonical financial plan"], firm: { required: true, buildBefore: true, buildAfter: true } };
export const bpwBusinessPlanResourcePack: ResourcePackDefinition = { id: "bpw.business-plan", version: "1.0.0", tier: "GOAL_SPECIFIC", path: "resources/business-plan/bpw", requiredSkills: compileBusinessPlanTemplate.requiredSkills, requiredCapabilities: ["firm"], installedFiles: ["RESOURCE.md", "manifest.yaml", "chapter-contract.yaml", "required-evidence.yaml", "evaluation-rubric.md", "sustainability-guide.md", "layout.md"], qualityGates: ["claim-traceability", "financial-reconciliation", "fact-preserving-edit", "privacy", "readiness"], dependencies: ["bpw.bmc", "bpw.finance"], compatibility: "Canonical BPW identifier retained; exact submission layout is unavailable and must not be inferred." };

export interface PlanStatement { statementId: string; text: string; statementType: typeof STATEMENT_TYPES[number]; evidenceIds: string[]; sourceArtifactIds: string[]; assumptionIds: string[]; calculationIds: string[]; contradictionIds: string[]; freshness: "CURRENT" | "STALE"; confidence: "LOW" | "MEDIUM" | "HIGH"; synthetic?: boolean; financialMetricId?: string; financialValue?: number; marketMetricId?: string; marketValue?: number; teamFactId?: string; capabilityId?: string; capabilityStatus?: "CURRENT" | "VALIDATED" | "PLANNED" | "HYPOTHESIZED"; containsPrivateCustomerData?: boolean; disclosureAuthorized?: boolean }
export interface SourceNote { sourceId: string; title: string; publisher: string; reference?: string; date?: string; retrievedAt?: string; evidenceType: string; claimsUsed: string[] }
export interface PlanRisk { riskId: string; description: string; impact: string; evidenceIds: string[]; assumptionIds: string[]; affectedChapter: BusinessPlanChapterId; mitigationGoal: string; status: string }
export interface BusinessPlanInput { companyId: string; goalId: string; projectId: string; planId: string; version: string; sourceStateVersion: string; bpwResourceVersion: string; compiledAt: Date; chapters: Record<BusinessPlanChapterId, PlanStatement[]>; executiveSummaryClaimIds: string[]; knownEvidenceIds: string[]; knownAssumptionIds: string[]; knownCalculationIds: string[]; knownContradictionIds: string[]; knownTeamFactIds: string[]; knownCapabilityIds: string[]; financialMetrics: Record<string, number | null>; marketMetrics: Record<string, number | null>; sources: SourceNote[]; risks: PlanRisk[]; staleDependencies: string[] }

export function chapterReadiness(statements: PlanStatement[]) {
  if (statements.some((s) => s.freshness === "STALE")) return "STALE" as const;
  const material = statements.filter((s) => s.statementType !== "UNKNOWN");
  if (!material.length) return "BLOCKED" as const;
  const assumed = material.filter((s) => ["FOUNDER_ASSUMPTION", "HYPOTHESIS"].includes(s.statementType)).length;
  const supported = material.filter((s) => s.evidenceIds.length || s.calculationIds.length).length;
  if (assumed > supported) return "ASSUMPTION_HEAVY" as const;
  return supported === material.length && !material.some((s) => s.contradictionIds.length) ? "SUPPORTED" as const : "PARTIALLY_SUPPORTED" as const;
}
export function compileBusinessPlan(input: BusinessPlanInput) {
  const bodyIds = new Map(BUSINESS_PLAN_CHAPTERS.filter((id) => id !== "executive-summary").flatMap((id) => input.chapters[id].map((statement) => [statement.statementId, statement] as const)));
  const executive = input.executiveSummaryClaimIds.map((id) => bodyIds.get(id)).filter((value): value is PlanStatement => Boolean(value)).map((value) => ({ ...value, statementId: `summary:${value.statementId}` }));
  const chapters = Object.fromEntries(BUSINESS_PLAN_CHAPTERS.map((id) => { const statements = id === "executive-summary" ? executive : input.chapters[id]; return [id, { id, statements, readiness: chapterReadiness(statements), openQuestions: statements.filter((s) => s.statementType === "UNKNOWN").map((s) => s.text), staleDependencies: statements.some((s) => s.freshness === "STALE") ? input.staleDependencies : [] }]; })) as Record<BusinessPlanChapterId, { id: BusinessPlanChapterId; statements: PlanStatement[]; readiness: typeof CHAPTER_READINESS[number]; openQuestions: string[]; staleDependencies: string[] }>;
  const readinesses = Object.values(chapters).map((chapter) => chapter.readiness);
  const readiness = readinesses.includes("STALE") ? "STALE" : readinesses.includes("BLOCKED") ? "NEEDS_EVIDENCE" : readinesses.some((r) => r !== "SUPPORTED") ? "COMPILABLE_WITH_GAPS" : "COMPILABLE";
  const material = Object.values(chapters).flatMap((c) => c.statements).filter((s) => s.statementType !== "UNKNOWN");
  const supported = material.filter((s) => s.evidenceIds.length || s.calculationIds.length || s.assumptionIds.length);
  return { plan: { version: input.version, compiledAt: input.compiledAt.toISOString(), companyId: input.companyId, sourceStateVersion: input.sourceStateVersion, bpwResourceVersion: input.bpwResourceVersion }, chapters, overall: { evidenceCoverage: material.length ? supported.length / material.length : 0, chapterReadiness: readiness, unresolvedCriticalClaims: material.filter((s) => !s.evidenceIds.length && !s.calculationIds.length && !s.assumptionIds.length).map((s) => s.statementId), staleDependencies: input.staleDependencies, contradictions: material.flatMap((s) => s.contradictionIds) } };
}
export function validateBusinessPlan(input: BusinessPlanInput, plan = compileBusinessPlan(input)) {
  const failures: string[] = [], evidence = new Set(input.knownEvidenceIds), assumptions = new Set(input.knownAssumptionIds), calculations = new Set(input.knownCalculationIds), contradictions = new Set(input.knownContradictionIds), bodyIds = new Set(BUSINESS_PLAN_CHAPTERS.filter((id) => id !== "executive-summary").flatMap((id) => input.chapters[id].map((s) => s.statementId)));
  for (const id of input.executiveSummaryClaimIds) if (!bodyIds.has(id)) failures.push(`Executive Summary claim ${id} is not present in a substantive chapter`);
  for (const chapter of BUSINESS_PLAN_CHAPTERS) for (const statement of plan.chapters[chapter].statements) {
    if (statement.synthetic && statement.statementType !== "HYPOTHESIS") failures.push(`${statement.statementId}: synthetic material cannot support a factual statement`);
    if (statement.statementType !== "UNKNOWN" && !statement.evidenceIds.length && !statement.calculationIds.length && !statement.assumptionIds.length) failures.push(`${statement.statementId}: unsupported material statement`);
    for (const id of statement.evidenceIds) if (!evidence.has(id)) failures.push(`${statement.statementId}: unresolved evidence ${id}`);
    for (const id of statement.assumptionIds) if (!assumptions.has(id)) failures.push(`${statement.statementId}: unresolved assumption ${id}`);
    for (const id of statement.calculationIds) if (!calculations.has(id)) failures.push(`${statement.statementId}: unresolved calculation ${id}`);
    for (const id of statement.contradictionIds) if (!contradictions.has(id)) failures.push(`${statement.statementId}: unresolved contradiction ${id}`);
    if (statement.financialMetricId && input.financialMetrics[statement.financialMetricId] !== statement.financialValue) failures.push(`${statement.statementId}: financial value does not reconcile`);
    if (statement.marketMetricId && input.marketMetrics[statement.marketMetricId] !== statement.marketValue) failures.push(`${statement.statementId}: market value does not reconcile`);
    if (statement.teamFactId && !input.knownTeamFactIds.includes(statement.teamFactId)) failures.push(`${statement.statementId}: unregistered team fact`);
    if (statement.capabilityId && !input.knownCapabilityIds.includes(statement.capabilityId)) failures.push(`${statement.statementId}: unregistered product capability`);
    if (statement.containsPrivateCustomerData && !statement.disclosureAuthorized) failures.push(`${statement.statementId}: private customer data is not authorized for disclosure`);
  }
  for (const source of input.sources) for (const claim of source.claimsUsed) if (!bodyIds.has(claim) && !claim.startsWith("summary:")) failures.push(`Source ${source.sourceId}: unresolved claim ${claim}`);
  return { pass: failures.length === 0, hardFailure: failures.length > 0, failures };
}
export function validateEditorialRevision(source: PlanStatement[], edited: Array<{ statementId: string; text: string }>) { const byId = new Map(source.map((s) => [s.statementId, s])); const failures: string[] = []; for (const item of edited) { const original = byId.get(item.statementId); if (!original) { failures.push(`Editorial output introduced claim ${item.statementId}`); continue; } const nums = (text: string) => text.match(/-?\d+(?:[.,]\d+)?%?/g) ?? []; if (JSON.stringify(nums(original.text)) !== JSON.stringify(nums(item.text))) failures.push(`${item.statementId}: editorial output changed material numbers`); } return { pass: failures.length === 0, failures }; }
export function businessPlanFingerprint(input: BusinessPlanInput) { return createHash("sha256").update(JSON.stringify({ sourceStateVersion: input.sourceStateVersion, bpwResourceVersion: input.bpwResourceVersion, chapters: input.chapters, financialMetrics: input.financialMetrics, marketMetrics: input.marketMetrics, sources: input.sources, staleDependencies: input.staleDependencies })).digest("hex"); }

function yaml(value: unknown, indent = 0): string { if (value === null) return "null"; if (Array.isArray(value)) return value.length ? value.map((v) => `${" ".repeat(indent)}- ${typeof v === "object" ? `\n${yaml(v, indent + 2)}` : String(v)}`).join("\n") : "[]"; if (typeof value === "object") return Object.entries(value as Record<string, unknown>).map(([k, v]) => `${" ".repeat(indent)}${k}: ${typeof v === "object" && v !== null ? `\n${yaml(v, indent + 2)}` : String(v)}`).join("\n"); return String(value); }
export function compileBusinessPlanArtifacts(input: BusinessPlanInput, plan = compileBusinessPlan(input)) { const statements = Object.values(plan.chapters).flatMap((c) => c.statements); const claims = statements.map((s) => ({ claimId: s.statementId, statement: s.text, classification: s.statementType, evidenceIds: s.evidenceIds, sourceArtifacts: s.sourceArtifactIds, calculationIds: s.calculationIds, assumptionIds: s.assumptionIds, contradictions: s.contradictionIds, freshness: s.freshness, confidence: s.confidence })); const md = ["# Business Plan", `Source state: ${input.sourceStateVersion}`, ...BUSINESS_PLAN_CHAPTERS.flatMap((id) => [`## ${id.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join(" ")}`, ...plan.chapters[id].statements.map((s) => s.text), `*Readiness: ${plan.chapters[id].readiness}*`, ""]), "## Overall Readiness", plan.overall.chapterReadiness].join("\n"); const risks = ["# Business Plan Risks", ...input.risks.map((r) => `- ${r.riskId} [${r.affectedChapter}]: ${r.description}; impact: ${r.impact}; next Goal: ${r.mitigationGoal}`)].join("\n"); return { "business-case/business-plan/BUSINESS_PLAN.yaml": yaml(plan), "business-case/business-plan/BUSINESS_PLAN.md": md, "business-case/business-plan/CLAIM_EVIDENCE_MAP.yaml": yaml({ claims }), "business-case/business-plan/SOURCES.yaml": yaml({ sources: input.sources }), "business-case/business-plan/BUSINESS_PLAN_RISKS.md": risks, "business-case/business-plan/READINESS.yaml": yaml({ readiness: plan.overall.chapterReadiness, chapters: Object.fromEntries(Object.entries(plan.chapters).map(([id, c]) => [id, c.readiness])), render: { status: "NOT_RENDERED", reason: "No verified canonical BPW DOCX/PDF template is available" } }) }; }

interface Hooks { firmBuild?(phase: "before" | "after"): Promise<{ success: boolean }>; writeFirm?(records: unknown[]): Promise<void>; writeArtifacts?(artifacts: Record<string, string>): Promise<void>; registerWorkProducts?(input: { companyId: string; goalId: string; projectId: string; artifacts: Record<string, string> }): Promise<void>; judge?(plan: ReturnType<typeof compileBusinessPlan>): Promise<{ verdict: string }> }
export async function evaluateBusinessPlan(validation: ReturnType<typeof validateBusinessPlan>, plan: ReturnType<typeof compileBusinessPlan>, hooks: Hooks) { if (!validation.pass) return { accepted: false, judgment: null }; if (hooks.firmBuild && !(await hooks.firmBuild("before")).success) throw new Error("Firm build before business plan failed"); await hooks.writeFirm?.([{ type: "decision", id: "business-plan-readiness", value: plan.overall.chapterReadiness }]); if (hooks.firmBuild && !(await hooks.firmBuild("after")).success) throw new Error("Firm build after business plan failed"); const judgment = await hooks.judge?.(plan); return { accepted: judgment?.verdict === "ACCEPT", judgment: judgment ?? null }; }
export function businessPlanService(db: Db, hooks: Hooks = {}) { const content = founderosContentService(db); async function activate(input: { companyId: string; parentGoalId: string; sourceRepository: string; sourceCommit: string }) { const source = { repository: input.sourceRepository, commit: input.sourceCommit }, goal = await content.instantiateGoal(input.companyId, source, compileBusinessPlanTemplate, input.parentGoalId), project = await content.activateSystem(input.companyId, source, businessPlanSystem, goal.goal.id, goal.goal.ownerAgentId!); const issues = []; for (const title of ["Assemble chapter evidence", "Compile substantive chapters", "Reconcile market and finance", "Compile executive summary", "Validate claim traceability", "Review risks and readiness", "Prepare rendering boundary"]) issues.push((await content.createGoalIssue(input.companyId, goal.goal.id, project.project.id, goal.goal.ownerAgentId!, title)).issue); return { goal: goal.goal, project: project.project, issues }; }
  async function compile(input: BusinessPlanInput) { const fingerprint = businessPlanFingerprint(input), existing = await db.select().from(businessPlans).where(and(eq(businessPlans.companyId, input.companyId), eq(businessPlans.sourceFingerprint, fingerprint))).limit(1).then((rows) => rows[0]); if (existing) return { plan: existing, reused: true }; const plan = compileBusinessPlan(input), validation = validateBusinessPlan(input, plan), artifacts = compileBusinessPlanArtifacts(input, plan); if (!validation.pass) return { plan, validation, artifacts, decision: "BUSINESS_PLAN_NOT_SUPPORTED", judgment: null, reused: false }; const evaluation = await evaluateBusinessPlan(validation, plan, hooks); await hooks.writeArtifacts?.(artifacts); await hooks.registerWorkProducts?.({ companyId: input.companyId, goalId: input.goalId, projectId: input.projectId, artifacts }); const decision = plan.overall.chapterReadiness === "COMPILABLE" ? "BUSINESS_PLAN_SUPPORTED" : "BUSINESS_PLAN_PARTIALLY_SUPPORTED"; const [row] = await db.insert(businessPlans).values({ companyId: input.companyId, goalId: input.goalId, projectId: input.projectId, planId: input.planId, version: input.version, sourceStateVersion: input.sourceStateVersion, sourceFingerprint: fingerprint, bpwResourceVersion: input.bpwResourceVersion, chapters: plan.chapters, claimEvidenceMap: { claims: Object.values(plan.chapters).flatMap((c) => c.statements) }, sources: { sources: input.sources }, risks: { risks: input.risks }, readiness: plan.overall, decision, status: input.staleDependencies.length ? "STALE_AT_COMPILE" : "CURRENT", renderStatus: "NOT_RENDERED", compiledAt: input.compiledAt }).returning(); await db.insert(artifactStaleness).values({ companyId: input.companyId, artifact: "pitch", reason: "Business Plan changed", evidenceId: input.planId, affectedDependency: "business-plan" }).onConflictDoNothing(); await db.insert(activityLog).values({ companyId: input.companyId, actorType: "system", actorId: businessPlanSystem.id, action: "business_plan.compiled", entityType: "business_plan", entityId: row.id, details: { decision, readiness: plan.overall.chapterReadiness } }); return { plan: row, compiled: plan, validation, artifacts, decision, judgment: evaluation.judgment, nextGoal: decision === "BUSINESS_PLAN_SUPPORTED" ? "compile-pitch" : null, reused: false }; }
  return { activate, compile }; }
