import { and, eq } from "drizzle-orm";
import type { Db } from "@paperclipai/db";
import { activityLog, approvals, contentCandidates, publishingAccounts, socialPublications } from "@paperclipai/db";

export const POSTIO_CONTRACT_STATUS = "BLOCKED_BY_API_CONTRACT" as const;
export const PUBLICATION_STATES = ["DRAFT", "CLAIM_VALIDATED", "CREATIVE_REVIEWED", "APPROVAL_REQUIRED", "APPROVED", "READY_FOR_POSTIO", "POSTIO_SUBMITTED", "SCHEDULED", "PUBLISHED", "FAILED"] as const;
export type SafePostioAccount = { provider: "POSTIO"; providerAccountId: string; platform: string; displayName?: string; capabilities: string[]; lastVerifiedAt: Date; status: string };
export type PreparedPublication = { publicationId: string; contentId: string; campaignId: string; providerAccountId: string; platform: "LINKEDIN" | string; text: string; mediaAssetIds: string[]; scheduledAt?: string };
export type PostioResult = { providerPublicationId?: string; status: "SUBMITTED" | "SCHEDULED" | "PUBLISHED" | "FAILED"; publicUrl?: string; publishedAt?: string; failureCode?: string; failureSummary?: string };
export interface PostioPublisher { contractStatus: "VERIFIED" | "BLOCKED_BY_API_CONTRACT"; getCapabilities(): Promise<string[]>; listConnectedAccounts(): Promise<SafePostioAccount[]>; preparePublication(input: PreparedPublication): Promise<PreparedPublication>; validatePublication(input: PreparedPublication): Promise<{ valid: boolean; errors: string[] }>; publish(input: PreparedPublication): Promise<PostioResult>; getPublicationStatus(providerPublicationId: string): Promise<PostioResult>; getPublicationResult(providerPublicationId: string): Promise<PostioResult> }
export class BlockedPostioPublisher implements PostioPublisher { contractStatus = POSTIO_CONTRACT_STATUS; private blocked(): never { throw new Error("Postio transport BLOCKED_BY_API_CONTRACT: live /api and source documentation were inaccessible; no request schema was guessed"); } async getCapabilities() { return this.blocked(); } async listConnectedAccounts() { return this.blocked(); } async preparePublication(_input: PreparedPublication) { return this.blocked(); } async validatePublication(_input: PreparedPublication) { return this.blocked(); } async publish(_input: PreparedPublication) { return this.blocked(); } async getPublicationStatus(_id: string) { return this.blocked(); } async getPublicationResult(_id: string) { return this.blocked(); } }
export type LinkedinCandidate = { contentId: string; campaignId: string; archetype: string; objective: string; audience: string; sourceClaimIds: string[]; evidenceIds: string[]; capabilities: Array<{ capabilityId: string; status: "LIVE_PRODUCT" | "PROTOTYPE" | "EXPERIMENTAL" | "PLANNED" | "CONCEPT" }>; hook: string; problem: string; insight: string; prototype: string; proof: string; whyItMatters: string; cta: string; media: Array<{ assetId: string; deploymentId: string; revision: string; capturedAt: string; route: string; status: "LIVE_PRODUCT" | "PROTOTYPE" | "MOCKUP" | "CONCEPT"; customerAuthorized?: boolean }>; claimMaturity: string };
export function validateLinkedinCandidate(c: LinkedinCandidate, knownClaims: string[], knownEvidence: string[], knownCapabilities: string[]) { const errors: string[] = []; if (!c.sourceClaimIds.length || c.sourceClaimIds.some(x => !knownClaims.includes(x))) errors.push("LinkedIn content requires resolved business claims"); if (!c.evidenceIds.length || c.evidenceIds.some(x => !knownEvidence.includes(x))) errors.push("LinkedIn content requires resolved evidence"); if (c.capabilities.some(x => !knownCapabilities.includes(x.capabilityId))) errors.push("Product capability is unresolved"); if (c.capabilities.some(x => ["PLANNED", "CONCEPT"].includes(x.status)) && /currently|automatically|does\b/i.test(c.prototype)) errors.push("Planned/concept capability is presented as current"); if (/revolutionary|game-changing|market leader/i.test([c.hook,c.problem,c.insight,c.prototype,c.proof,c.whyItMatters].join(" "))) errors.push("Unsupported promotional superlative"); if (c.media.some(x => ["MOCKUP", "CONCEPT"].includes(x.status)) && /live|current/i.test(c.proof)) errors.push("Mockup/concept is presented as live product"); if (c.media.some(x => x.customerAuthorized === false)) errors.push("Customer media is not authorized"); return { valid: !errors.length, errors }; }
export function linkedinBody(c: LinkedinCandidate) { return [c.hook, c.problem, c.insight, c.prototype, c.proof, c.whyItMatters, c.cta].filter(Boolean).join("\n\n"); }
export function assertPostioApproval(approval: { status:string; type:string } | undefined) { if(approval?.status!=="approved"||approval.type!=="external_action") throw new Error("Approved native external-action approval required before Postio submission"); }
export function mapPostioResult(result:PostioResult) { const status=result.status==="PUBLISHED"?"PUBLISHED":result.status==="FAILED"?"FAILED":result.status==="SCHEDULED"?"SCHEDULED":"POSTIO_SUBMITTED"; return {status,retryEligible:result.status==="FAILED"&&!['AUTHORIZATION','ACCOUNT_DISCONNECTED','INVALID_CONTENT','PLATFORM_POLICY'].includes(result.failureCode??"")}; }
export function contentPublishingService(db: Db, postio: PostioPublisher = new BlockedPostioPublisher()) { const activity = (companyId:string, action:string, entityId:string, details:Record<string,unknown>) => db.insert(activityLog).values({ companyId, actorType:"system", actorId:"content-publishing", action, entityType:"social_publication", entityId, details }); return {
  contractStatus: postio.contractStatus,
  async syncAccounts(companyId:string) { const accounts = await postio.listConnectedAccounts(); for (const a of accounts) await db.insert(publishingAccounts).values({ companyId, ...a }).onConflictDoUpdate({ target:[publishingAccounts.companyId,publishingAccounts.provider,publishingAccounts.providerAccountId], set:{ platform:a.platform,displayName:a.displayName,capabilities:a.capabilities,status:a.status,lastVerifiedAt:a.lastVerifiedAt } }); return accounts; },
  async saveCandidate(companyId:string,c:LinkedinCandidate,knownClaims:string[],knownEvidence:string[],knownCapabilities:string[]) { const validation=validateLinkedinCandidate(c,knownClaims,knownEvidence,knownCapabilities); if(!validation.valid) throw new Error(validation.errors.join("; ")); return db.insert(contentCandidates).values({companyId,contentId:c.contentId,campaignId:c.campaignId,platform:"LINKEDIN",archetype:c.archetype,objective:c.objective,audience:c.audience,sourceClaimIds:c.sourceClaimIds,evidenceIds:c.evidenceIds,capabilityIds:c.capabilities.map(x=>x.capabilityId),copy:{hook:c.hook,body:linkedinBody(c),cta:c.cta},media:c.media,claimMaturity:c.claimMaturity,approvalStatus:"REQUIRED",publicationStatus:"CLAIM_VALIDATED"}).returning().then(r=>r[0]); },
  async publish(companyId:string,input:PreparedPublication,approvalId:string) { const existing=await db.select().from(socialPublications).where(and(eq(socialPublications.companyId,companyId),eq(socialPublications.publicationId,input.publicationId))).limit(1).then(r=>r[0]); if(existing?.status==="PUBLISHED"||existing?.status==="POSTIO_SUBMITTED"||existing?.status==="SCHEDULED") return { publication:existing,reused:true }; const approval=await db.select().from(approvals).where(and(eq(approvals.companyId,companyId),eq(approvals.id,approvalId))).limit(1).then(r=>r[0]); assertPostioApproval(approval); const account=await db.select().from(publishingAccounts).where(and(eq(publishingAccounts.companyId,companyId),eq(publishingAccounts.providerAccountId,input.providerAccountId))).limit(1).then(r=>r[0]); if(!account||account.provider!=="POSTIO"||account.status!=="CONNECTED") throw new Error("Postio account is not connected"); const validation=await postio.validatePublication(input); if(!validation.valid) throw new Error(validation.errors.join("; ")); const result=await postio.publish(input), {status,retryEligible}=mapPostioResult(result); const [row]=await db.insert(socialPublications).values({companyId,publicationId:input.publicationId,contentId:input.contentId,campaignId:input.campaignId,provider:"POSTIO",platform:input.platform,providerAccountId:input.providerAccountId,providerPublicationId:result.providerPublicationId,status,publicUrl:result.publicUrl,failureCode:result.failureCode,failureSummary:result.failureSummary?.slice(0,500),retryEligible,submittedAt:new Date(),publishedAt:result.publishedAt?new Date(result.publishedAt):undefined}).onConflictDoNothing().returning(); await activity(companyId,result.status==="FAILED"?"postio.publication_failed":"postio.publication_submitted",row?.id??existing?.id??input.publicationId,{status,retryEligible,campaignWake:["PUBLISHED","FAILED"].includes(status)}); return {publication:row,result,reused:false}; }
}; }
