import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import type { Db } from "@paperclipai/db";
import { activityLog, approvals, crowdfundingCampaigns, crowdfundingEvents, issues, marketWaits } from "@paperclipai/db";
import { founderosContentService, type GoalTemplate, type ResourcePackDefinition, type SystemDefinition } from "./founderos-content/index.js";
import { POSTIO_CONTRACT_STATUS } from "./content-publishing.js";

export const CROWDFUNDING_DECISIONS = ["PROCEED_TO_PRELAUNCH", "BUILD_AUDIENCE_FIRST", "REFINE_OFFER", "FIX_REWARD_ECONOMICS", "VALIDATE_FULFILLMENT", "GATHER_MORE_PROOF", "CROWDFUNDING_NOT_CURRENTLY_SUPPORTED"] as const;
export const CROWDFUNDING_EVENTS = ["CAMPAIGN_VIEW", "FOLLOW", "PLEDGE_STARTED", "PLEDGE_CREATED", "PLEDGE_CHANGED", "PLEDGE_CANCELLED", "REWARD_SELECTED", "REFERRAL", "CAMPAIGN_SHARE", "FUNDING_MILESTONE", "CAMPAIGN_FUNDED", "CAMPAIGN_ENDED"] as const;
export const READINESS_STATES = ["READY_TO_LAUNCH", "READY_WITH_GAPS", "BUILD_AUDIENCE_FIRST", "FIX_ECONOMICS", "FIX_FULFILLMENT", "RESOLVE_CLAIMS", "PLATFORM_BLOCKED"] as const;

export const kickstarterSystem: SystemDefinition = {
  id: "kickstarter-crowdfunding", version: "1.0.0", title: "Kickstarter / Crowdfunding",
  purpose: "Evaluate, prepare, govern, launch manually, and learn from an evidence-backed crowdfunding campaign.",
  stateDependencies: ["Pitch Framework", "Content & Distribution", "GTM Campaigns", "financial plan", "product capability state"],
  goals: ["prepare-kickstarter-case", "build-kickstarter-campaign", "prepare-kickstarter-prelaunch", "produce-kickstarter-assets", "prepare-kickstarter-launch-content", "launch-kickstarter-campaign", "measure-kickstarter-campaign", "optimize-kickstarter-campaign"],
  expectedOutputs: ["campaign/kickstarter/**"], wakeConditions: ["verified_campaign_event", "campaign_deadline_reached", "operator_resumed"],
  evidenceFeedbackLoop: ["case -> prelaunch -> governed manual launch -> verified behavior -> learning"], stopConditions: ["campaign decision", "operator stop"],
};
const titles: Record<string, string> = { "prepare-kickstarter-case": "Prepare Case", "build-kickstarter-campaign": "Build Campaign", "prepare-kickstarter-prelaunch": "Prepare Prelaunch", "produce-kickstarter-assets": "Produce Assets", "prepare-kickstarter-launch-content": "Prepare Launch Content", "launch-kickstarter-campaign": "Launch", "measure-kickstarter-campaign": "Measure", "optimize-kickstarter-campaign": "Optimize" };
export const kickstarterGoalTemplates: GoalTemplate[] = kickstarterSystem.goals.map((id, index) => ({
  id, version: "1.0.0", system: kickstarterSystem.id, title: titles[id], objective: `${titles[id]} using current, attributable evidence and native Paperclip governance.`, recommendedOwnerRole: "crowdfunding",
  requiredSkills: ["bpw-evidence-and-source-discipline", "content-strategy", "creative-generation-review-loop"], supportPacks: [{ id: "crowdfunding.kickstarter", version: "1.0.0", required: true }, { id: "content.core", version: "1.0.0", required: true }, { id: "gtm.campaign-core", version: "1.0.0", required: true }], requiredCapabilities: ["firm"],
  inputPaths: ["business-case/**", "pitch/**", "marketing/**", "product/**", "evidence/**", "firm/**"], outputPaths: ["campaign/kickstarter/**"],
  acceptanceCriteria: ["Claims and capabilities preserve provenance and maturity", "Economics reconcile without invented inputs", "Consequential external actions have native approval", "Firm builds"],
  cannotCompleteIf: ["Unknown shipping, fee, tax, capacity, or date is invented", "Planned functionality or mockups are presented as live", "Unverified events are ingested", "A platform contract is invented"],
  writeScope: ["campaign/kickstarter/**", "firm/**"], externalActionPolicy: "APPROVAL_REQUIRED", wakeConditions: kickstarterSystem.wakeConditions, nextGoalHints: index + 1 < kickstarterSystem.goals.length ? [kickstarterSystem.goals[index + 1]] : [], prerequisites: index ? [kickstarterSystem.goals[index - 1]] : [], evidenceRequirements: ["claim IDs", "evidence IDs", "capability status", "source freshness"], firm: { required: true, buildBefore: true, buildAfter: true },
}));
export const kickstarterResourcePack: ResourcePackDefinition = { id: "crowdfunding.kickstarter", version: "1.0.0", tier: "GOAL_SPECIFIC", path: "resources/crowdfunding/kickstarter", requiredSkills: ["bpw-evidence-and-source-discipline"], requiredCapabilities: ["firm"], installedFiles: ["RESOURCE.md", "manifest.yaml", "campaign-page-contract.yaml", "campaign-story-framework.md", "reward-tier-framework.md", "faq-template.md", "risk-disclosure-guide.md", "visual-shot-list.md", "campaign-video-structure.md", "prelaunch-checklist.md", "launch-calendar.yaml", "update-template.md", "social-launch-sequence.md", "email-launch-sequence.md", "evidence-map.md", "quality-gate.md"], qualityGates: ["evidence-provenance", "economics-safety", "capability-truth", "approval-governance"], dependencies: ["content.core", "gtm.campaign-core"], compatibility: "FounderOS Pitch and Content/GTM contracts" };

export type Money = { amountCents: number | null; currency: string; status: "EVIDENCED" | "ASSUMPTION" | "UNKNOWN"; evidenceIds: string[] };
export type Suitability = { crowdfundingFit: number; audienceStrength: number; demonstrableProduct: number; storyStrength: number; rewardFeasibility: number; fulfillmentRisk: number; economics: number; capitalNeed: number; prelaunchReadiness: number; proofEvidenceIds: string[] };
export type RewardTier = { id: string; name: string; price: Money; cost: Money; fulfillmentComplexity: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN"; capacity: number | null; capacityStatus: "EVIDENCED" | "ASSUMPTION" | "UNKNOWN"; deliveryDate?: string; deliveryEvidenceIds?: string[] };
export type Claim = { claimId: string; text: string; evidenceIds: string[]; maturity: "VALIDATED" | "SUPPORTED" | "HYPOTHESIS"; allowedLanguage: string; capabilityStatus: "LIVE_PRODUCT" | "PROTOTYPE" | "MOCKUP" | "CONCEPT" | "PLANNED"; freshThrough?: string; customerIdentifying?: boolean; customerAuthorized?: boolean };
export type CampaignInput = { campaignId: string; version: string; sourceStateVersion: string; suitability: Suitability; economics: { capitalRequirement: Money; productionCost: Money; fulfillment: Money; platformPaymentFees: Money; marketingSpend: Money; contingency: Money; fundingTarget: Money }; rewards: RewardTier[]; claims: Claim[]; story: { problem: string; whyItMatters: string; learning: string; prototype: string; proof: string; whyCrowdfunding: string; fundingEnables: string; roadmap: string; risks: string; cta: string }; assets: Array<{ id: string; kind: string; status: "LIVE_PRODUCT" | "PROTOTYPE" | "MOCKUP" | "CONCEPT"; sourceRef: string; customerAuthorized?: boolean }>; prelaunch: { audienceEvidenceIds: string[]; channels: string[]; emailProviderVerified: boolean; postioContractStatus: string }; fulfillment: { provisioningCapacity: number | null; supportCapacity: number | null; computeCapacity: number | null; dependencies: string[]; evidenceIds: string[] }; stress: { backerVolumes: number[]; rewardMixDefined: boolean; supportPerBackerMinutes: number | null; computePerBacker: number | null; cancellationRate: number | null; campaignSpend: Money }; platformIntegrationVerified: boolean; sourceRefs: string[]; compiledAt: string };

const known = (money: Money) => money.amountCents !== null && money.status !== "UNKNOWN";
export function decideSuitability(value: Suitability) { if (!value.proofEvidenceIds.length) return "GATHER_MORE_PROOF"; if (value.economics < 3) return "FIX_REWARD_ECONOMICS"; if (value.fulfillmentRisk < 3) return "VALIDATE_FULFILLMENT"; if (value.audienceStrength < 3 || value.prelaunchReadiness < 3) return "BUILD_AUDIENCE_FIRST"; if (value.crowdfundingFit < 3) return "CROWDFUNDING_NOT_CURRENTLY_SUPPORTED"; if (value.rewardFeasibility < 3 || value.storyStrength < 3) return "REFINE_OFFER"; return "PROCEED_TO_PRELAUNCH"; }
export function validateEconomics(economics: CampaignInput["economics"], tiers: RewardTier[]) { const errors: string[] = []; const components = [economics.capitalRequirement, economics.productionCost, economics.fulfillment, economics.platformPaymentFees, economics.marketingSpend, economics.contingency]; if (!components.every(known) || !known(economics.fundingTarget)) errors.push("Funding target inputs must be evidenced or explicit assumptions; unknown amounts cannot be reconciled"); else { const required = components.reduce((sum, item) => sum + item.amountCents!, 0); if (economics.fundingTarget.amountCents !== required) errors.push(`Funding target must equal reconciled requirement (${required})`); } for (const tier of tiers) { if (!known(tier.price) || !known(tier.cost)) errors.push(`Reward ${tier.id} has unknown price or cost`); else if (tier.price.amountCents! <= tier.cost.amountCents!) errors.push(`Reward ${tier.id} has non-positive contribution`); if (tier.capacity === null || tier.capacityStatus === "UNKNOWN") errors.push(`Reward ${tier.id} capacity is unknown`); if (tier.deliveryDate && !tier.deliveryEvidenceIds?.length) errors.push(`Reward ${tier.id} delivery date lacks evidence`); } return { valid: !errors.length, errors, tiers: tiers.map((tier) => ({ ...tier, contributionCents: known(tier.price) && known(tier.cost) ? tier.price.amountCents! - tier.cost.amountCents! : null, safe: !errors.some((error) => error.includes(`Reward ${tier.id}`)) })) }; }
export function validateClaims(claims: Claim[], assets: CampaignInput["assets"], now = new Date()) { const errors: string[] = []; for (const claim of claims) { if (!claim.evidenceIds.length) errors.push(`Claim ${claim.claimId} lacks evidence`); if (["PLANNED", "MOCKUP", "CONCEPT"].includes(claim.capabilityStatus) && /\b(live|currently|available now|already)\b/i.test(claim.text)) errors.push(`Claim ${claim.claimId} presents ${claim.capabilityStatus} as live`); if (claim.freshThrough && new Date(claim.freshThrough) < now) errors.push(`Claim ${claim.claimId} is stale`); if (claim.customerIdentifying && !claim.customerAuthorized) errors.push(`Claim ${claim.claimId} lacks customer media authorization`); } for (const asset of assets) if (["MOCKUP", "CONCEPT"].includes(asset.status) && /live|product[-_ ]?demo/i.test(asset.kind)) errors.push(`Asset ${asset.id} presents ${asset.status} as live`); return { valid: !errors.length, errors }; }
export function stressFulfillment(input: CampaignInput) { const max = Math.max(...input.stress.backerVolumes, 0), fulfillment = input.fulfillment, errors: string[] = []; if (!input.stress.rewardMixDefined) errors.push("Reward mix is not defined"); if ([fulfillment.provisioningCapacity, fulfillment.supportCapacity, fulfillment.computeCapacity, input.stress.supportPerBackerMinutes, input.stress.computePerBacker, input.stress.cancellationRate].some((value) => value === null)) errors.push("Stress-test inputs are incomplete"); if (fulfillment.provisioningCapacity !== null && max > fulfillment.provisioningCapacity) errors.push("Backer volume exceeds provisioning capacity"); if (fulfillment.supportCapacity !== null && input.stress.supportPerBackerMinutes !== null && max * input.stress.supportPerBackerMinutes > fulfillment.supportCapacity) errors.push("Backer volume exceeds support capacity"); if (fulfillment.computeCapacity !== null && input.stress.computePerBacker !== null && max * input.stress.computePerBacker > fulfillment.computeCapacity) errors.push("Backer volume exceeds compute capacity"); return { safe: !errors.length, maxBackers: max, errors }; }
export function assessReadiness(input: CampaignInput) { const economics = validateEconomics(input.economics, input.rewards), claims = validateClaims(input.claims, input.assets), fulfillment = stressFulfillment(input), decision = decideSuitability(input.suitability); let overall: string = "READY_TO_LAUNCH"; if (decision === "BUILD_AUDIENCE_FIRST") overall = "BUILD_AUDIENCE_FIRST"; else if (!economics.valid) overall = "FIX_ECONOMICS"; else if (!fulfillment.safe) overall = "FIX_FULFILLMENT"; else if (!claims.valid) overall = "RESOLVE_CLAIMS"; else if (!input.platformIntegrationVerified) overall = "PLATFORM_BLOCKED"; return { overall, dimensions: { CASE: decision, ECONOMICS: economics.valid ? "READY" : "GAP", STORY: input.story.proof ? "READY" : "GAP", REWARDS: economics.valid ? "READY" : "GAP", PRODUCT_PROOF: input.suitability.proofEvidenceIds.length ? "READY" : "GAP", VIDEO: input.assets.some((asset) => asset.kind === "VIDEO") ? "READY" : "GAP", FAQ: "READY", RISKS: input.story.risks ? "READY" : "GAP", PRELAUNCH_AUDIENCE: input.prelaunch.audienceEvidenceIds.length ? "READY" : "GAP", CONTENT: "READY", FULFILLMENT: fulfillment.safe ? "READY" : "GAP", PLATFORM: input.platformIntegrationVerified ? "VERIFIED" : "MANUAL_EXTERNAL_ACTION", ANALYTICS: "VERIFIED_EVENTS_ONLY" }, economics, claims, fulfillment }; }
const json = (value: unknown) => JSON.stringify(value, null, 2);
export function campaignArtifacts(input: CampaignInput) { const readiness = assessReadiness(input), base = "campaign/kickstarter/"; return { [base + "KICKSTARTER_CASE.yaml"]: json({ decision: decideSuitability(input.suitability), assessment: input.suitability }), [base + "KICKSTARTER_CASE.md"]: `# Kickstarter Case\n\nDecision: **${decideSuitability(input.suitability)}**\n`, [base + "CAMPAIGN_ECONOMICS.yaml"]: json({ ...input.economics, validation: readiness.economics }), [base + "REWARD_TIERS.yaml"]: json(readiness.economics.tiers), [base + "CAMPAIGN_STORY.md"]: `# Campaign Story\n\n## Problem\n${input.story.problem}\n\n## Why it matters\n${input.story.whyItMatters}\n\n## What we learned\n${input.story.learning}\n\n## Current prototype\n${input.story.prototype}\n\n## Proof\n${input.story.proof}\n\n## Why crowdfunding\n${input.story.whyCrowdfunding}\n\n## What funding enables\n${input.story.fundingEnables}\n\n## Roadmap\n${input.story.roadmap}\n\n## Risks\n${input.story.risks}\n\n## CTA\n${input.story.cta}\n`, [base + "KICKSTARTER_PAGE.yaml"]: json({ story: input.story, claimIds: input.claims.map((claim) => claim.claimId), rewardIds: input.rewards.map((reward) => reward.id) }), [base + "KICKSTARTER_PAGE.md"]: `# Kickstarter Campaign Page\n\n${input.story.problem}\n\n${input.story.prototype}\n\n${input.story.proof}\n`, [base + "CAMPAIGN_CLAIM_MAP.yaml"]: json(input.claims), [base + "VIDEO_SCRIPT.md"]: `# Video Script\n\nUse only labeled, source-backed product footage.\n\n${input.story.problem}\n${input.story.prototype}\n${input.story.cta}\n`, [base + "SHOT_LIST.yaml"]: json(input.assets), [base + "FAQ.md"]: "# FAQ\n\nDelivery, shipping, tax, and platform terms remain UNKNOWN until verified; do not promise them.\n", [base + "RISKS_AND_CHALLENGES.md"]: `# Risks and Challenges\n\n${input.story.risks}\n\n${readiness.fulfillment.errors.join("\n") || "No identified capacity breach in supplied scenarios."}\n`, [base + "PRELAUNCH_PLAN.yaml"]: json(input.prelaunch), [base + "PRELAUNCH_PLAN.md"]: `# Prelaunch Plan\n\nChannels: ${input.prelaunch.channels.join(", ")}\n\nPostio: ${POSTIO_CONTRACT_STATUS}; email: ${input.prelaunch.emailProviderVerified ? "PROVIDER_VERIFIED" : "READY_FOR_SEND_ONLY"}.\n`, [base + "EMAIL_SEQUENCE.yaml"]: json({ status: "READY_FOR_SEND", sent: false }), [base + "SOCIAL_SEQUENCE.yaml"]: json({ status: input.prelaunch.postioContractStatus === "VERIFIED" ? "APPROVAL_REQUIRED" : "READY_FOR_POSTIO", published: false }), [base + "READINESS.yaml"]: json(readiness) }; }
export function validateVerifiedEvent(event: { eventType: string; source: string; verified: boolean; amount?: string }) { const errors: string[] = []; if (!CROWDFUNDING_EVENTS.includes(event.eventType as typeof CROWDFUNDING_EVENTS[number])) errors.push("Unknown campaign event"); if (!event.verified || !event.source) errors.push("Only real verified events may be ingested"); if (event.eventType === "PLEDGE_STARTED" && event.amount) errors.push("Pledge intent cannot be recorded as received revenue"); return { valid: !errors.length, errors }; }

export function crowdfundingService(db: Db) { const content = founderosContentService(db); return {
  async activate(input: { companyId: string; goalId: string; parentGoalId: string; sourceRepository: string; sourceCommit: string }) { const goalTemplate = kickstarterGoalTemplates.find((goal) => goal.id === input.goalId); if (!goalTemplate) throw new Error("Goal is not registered for Kickstarter / Crowdfunding"); const source = { repository: input.sourceRepository, commit: input.sourceCommit }, goal = await content.instantiateGoal(input.companyId, source, goalTemplate, input.parentGoalId), project = await content.activateSystem(input.companyId, source, kickstarterSystem, goal.goal.id, goal.goal.ownerAgentId!); return { goal: goal.goal, project: project.project }; },
  async compile(companyId: string, input: CampaignInput) { const readiness = assessReadiness(input), sourceFingerprint = createHash("sha256").update(JSON.stringify({ sourceStateVersion: input.sourceStateVersion, sourceRefs: input.sourceRefs, economics: input.economics, claims: input.claims, assets: input.assets })).digest("hex"), existing = await db.select().from(crowdfundingCampaigns).where(and(eq(crowdfundingCampaigns.companyId, companyId), eq(crowdfundingCampaigns.sourceFingerprint, sourceFingerprint))).limit(1).then((rows) => rows[0]); if (existing) return { campaign: existing, artifacts: campaignArtifacts(input), reused: true }; const [campaign] = await db.insert(crowdfundingCampaigns).values({ companyId, campaignId: input.campaignId, version: input.version, sourceStateVersion: input.sourceStateVersion, sourceFingerprint, campaign: input, readiness: readiness.overall, status: "DRAFT" }).returning(); return { campaign, artifacts: campaignArtifacts(input), reused: false }; },
  async launch(companyId: string, campaignId: string, approvalId: string) { const approval = await db.select().from(approvals).where(and(eq(approvals.companyId, companyId), eq(approvals.id, approvalId))).limit(1).then((rows) => rows[0]); if (approval?.status !== "approved" || approval.type !== "external_action") throw new Error("Approved native external-action approval required"); const campaign = await db.select().from(crowdfundingCampaigns).where(and(eq(crowdfundingCampaigns.companyId, companyId), eq(crowdfundingCampaigns.campaignId, campaignId))).limit(1).then((rows) => rows[0]); if (!campaign) throw new Error("Campaign not found"); await db.insert(activityLog).values({ companyId, actorType: "system", actorId: "kickstarter-crowdfunding", action: "crowdfunding.manual_launch_authorized", entityType: "crowdfunding_campaign", entityId: campaign.id, details: { snapshotVersion: campaign.version, sourceFingerprint: campaign.sourceFingerprint, immutableSnapshot: true, mode: "MANUAL_EXTERNAL_ACTION", platformIntegration: "PLATFORM_BLOCKED" } }); return { campaign, launchState: "MANUAL_EXTERNAL_ACTION", platformState: "PLATFORM_BLOCKED" }; },
  async ingest(companyId: string, event: { eventId: string; campaignId: string; eventType: string; occurredAt: Date; source: string; verified: boolean; amount?: string; currency?: string; subjectRef?: string; evidenceIds: string[]; metadata: Record<string, unknown>; attribution: "ATTRIBUTED" | "ASSISTED" | "UNKNOWN" }) { const validation = validateVerifiedEvent(event); if (!validation.valid) throw new Error(validation.errors.join("; ")); const { verified: _verified, attribution, ...record } = event; return db.insert(crowdfundingEvents).values({ companyId, ...record, metadata: { ...record.metadata, verified: true, attribution } }).onConflictDoNothing().returning().then((rows) => rows[0]); },
  async wait(companyId: string, campaignId: string, issueId: string) { const issue = await db.select().from(issues).where(and(eq(issues.companyId, companyId), eq(issues.id, issueId))).limit(1).then((rows) => rows[0]); if (!issue?.goalId || !issue.projectId) throw new Error("Native company-scoped Issue required"); const campaign = await db.select().from(crowdfundingCampaigns).where(and(eq(crowdfundingCampaigns.companyId, companyId), eq(crowdfundingCampaigns.campaignId, campaignId))).limit(1).then((rows) => rows[0]); if (!campaign || !["MANUALLY_LAUNCHED", "LIVE"].includes(campaign.status)) throw new Error("WAITING_FOR_MARKET requires verified external launch"); const [wait] = await db.insert(marketWaits).values({ companyId, goalId: issue.goalId, projectId: issue.projectId, issueId, stage: "CROWDFUNDING_CAMPAIGN", reason: "Waiting for verified external campaign behavior", wakeConditions: kickstarterSystem.wakeConditions.map((type) => ({ type })), status: "WAITING_FOR_MARKET" }).onConflictDoNothing().returning(); await db.insert(activityLog).values({ companyId, actorType: "system", actorId: "kickstarter-crowdfunding", action: "crowdfunding.waiting_for_market", entityType: "crowdfunding_campaign", entityId: campaign.id, details: { julesPolling: false } }); return wait; },
}; }
