import type { CompanyRepositoryInspection, FounderOsRepositoryWriter } from "./founderos-bootstrap.js";
function githubHeaders(token = process.env.GITHUB_TOKEN) { const headers:Record<string,string>={accept:"application/vnd.github+json","content-type":"application/json","x-github-api-version":"2022-11-28","user-agent":"paperclip-founderos-bootstrap"}; if(token)headers.authorization=`Bearer ${token}`; return headers; }
// GitHub answers a burst of parallel write requests with 429/5xx far more often than
// it fails outright, and a single bootstrap creates one blob per managed file. Retry the
// retryable statuses and keep the burst narrow so one transient 503 cannot abort an import.
const RETRYABLE_GITHUB_STATUS = new Set([429, 500, 502, 503, 504]);
export const githubRequestRuntime = { fetch: (...args: Parameters<typeof fetch>) => fetch(...args), sleep: (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms)), attempts: 4, blobConcurrency: 4 };
export function githubRetryDelayMs(attempt: number, retryAfter?: string | null): number { const seconds = retryAfter === undefined || retryAfter === null ? Number.NaN : Number(retryAfter); if (Number.isFinite(seconds) && seconds >= 0) return Math.min(30_000, seconds * 1000); return Math.min(8_000, 500 * 2 ** attempt); }
export async function mapWithConcurrency<T, R>(items: T[], limit: number, fn: (item: T, index: number) => Promise<R>): Promise<R[]> { const results = new Array<R>(items.length); let cursor = 0; const lanes = Math.max(1, Math.min(limit, items.length)); await Promise.all(Array.from({ length: lanes }, async () => { for (let index = cursor++; index < items.length; index = cursor++) results[index] = await fn(items[index]!, index); })); return results; }
async function request<T>(url:string, init:RequestInit={}, token?:string):Promise<T>{let status=0;for(let attempt=0;attempt<githubRequestRuntime.attempts;attempt++){const response=await githubRequestRuntime.fetch(url,{...init,headers:{...githubHeaders(token),...(init.headers??{})}});if(response.ok)return response.json() as Promise<T>;status=response.status;if(!RETRYABLE_GITHUB_STATUS.has(status)||attempt===githubRequestRuntime.attempts-1)break;await githubRequestRuntime.sleep(githubRetryDelayMs(attempt,response.headers.get("retry-after")));}throw new Error(`GitHub bootstrap request failed (${status})`)}
export async function inspectCompanyRepository(repository:string, ref?:string, token=process.env.GITHUB_TOKEN):Promise<CompanyRepositoryInspection>{if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository))throw new Error("Invalid GitHub repository identity");const meta=await request<any>(`https://api.github.com/repos/${repository}`,{},token);const branch=ref??meta.default_branch;const commit=await request<any>(`https://api.github.com/repos/${repository}/commits/${encodeURIComponent(branch)}`,{},token);const tree=await request<any>(`https://api.github.com/repos/${repository}/git/trees/${commit.sha}?recursive=1`,{},token);return{repository,repositoryId:String(meta.id),defaultBranch:meta.default_branch,commitSha:commit.sha,paths:(tree.tree??[]).map((x:any)=>String(x.path)),readText:async(path)=>{const response=await fetch(`https://raw.githubusercontent.com/${repository}/${encodeURIComponent(commit.sha)}/${path.split("/").map(encodeURIComponent).join("/")}`,{headers:githubHeaders(token)});return response.ok?response.text():null}}}
export function githubFounderOsRepositoryWriter(token=process.env.GITHUB_TOKEN):FounderOsRepositoryWriter{if(!token)throw new Error("GITHUB_TOKEN is required to create the bootstrap pull request");return{createBootstrapPullRequest:async(input)=>{const base=await request<any>(`https://api.github.com/repos/${input.repository}/git/ref/heads/${encodeURIComponent(input.baseBranch)}`,{},token);const branch=`founderos/bootstrap-${Date.now()}`;await request(`https://api.github.com/repos/${input.repository}/git/refs`,{method:"POST",body:JSON.stringify({ref:`refs/heads/${branch}`,sha:base.object.sha})},token);const blobs=await mapWithConcurrency(Object.entries(input.files),githubRequestRuntime.blobConcurrency,async([path,content])=>({path,mode:"100644",type:"blob",sha:(await request<any>(`https://api.github.com/repos/${input.repository}/git/blobs`,{method:"POST",body:JSON.stringify({content,encoding:"utf-8"})},token)).sha}));const baseCommit=await request<any>(`https://api.github.com/repos/${input.repository}/git/commits/${base.object.sha}`,{},token);const tree=await request<any>(`https://api.github.com/repos/${input.repository}/git/trees`,{method:"POST",body:JSON.stringify({base_tree:baseCommit.tree.sha,tree:blobs})},token);const commit=await request<any>(`https://api.github.com/repos/${input.repository}/git/commits`,{method:"POST",body:JSON.stringify({message:input.title,tree:tree.sha,parents:[base.object.sha]})},token);await request(`https://api.github.com/repos/${input.repository}/git/refs/heads/${branch}`,{method:"PATCH",body:JSON.stringify({sha:commit.sha})},token);const pr=await request<any>(`https://api.github.com/repos/${input.repository}/pulls`,{method:"POST",body:JSON.stringify({title:input.title,head:branch,base:input.baseBranch,body:"Installs versioned FounderOS operating context and empty Firm structure. No business facts are introduced."})},token);return{url:pr.html_url,branch,commitSha:commit.sha}}}}
