import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import type { Db } from "@paperclipai/db";
import { activityLog, agents, artifactStaleness, companyDeployments, companyRepositoryBindings, issues, runtimeObservations } from "@paperclipai/db";
import { founderosContentService, type GoalTemplate, type SystemDefinition } from "./founderos-content/index.js";

export const OBSERVATION_TYPES = ["DEPLOYMENT_FAILED","STARTUP_ERROR","HEALTHCHECK_FAILED","SERVER_ERROR","BROKEN_ROUTE","FUNCTIONAL_REGRESSION","PERFORMANCE_DEGRADATION","ANALYTICS_REGRESSION","VALIDATION_BLOCKER","USER_REPORTED_DEFECT","PRODUCT_LEARNING"] as const;
export type ObservationType = typeof OBSERVATION_TYPES[number];
export const PRODUCT_DECISIONS = ["FIX","SMALL_IMPROVEMENT","EXPERIMENT_FIRST","BACKLOG","REJECT","ESCALATE"] as const;
export const PRIMARY_NEXT_GOALS = ["observe-product-usage","validate-value-realization","validate-retention"] as const;
export const mvpReliabilitySystem:SystemDefinition={id:"mvp-reliability",version:"1.0.0",title:"MVP Reliability & Product Learning",purpose:"Continuously keep the existing GitHub MVP healthy and turn actual runtime and product evidence into bounded repair or learning work.",stateDependencies:["company repository binding","registered runtime"],goals:["maintain-mvp-reliability"],expectedOutputs:["native Issues","validated PRs","product/PRODUCT_LEARNING.md"],wakeConditions:["runtime_observation","deployment_changed","user_reported_defect","product_learning_received"],evidenceFeedbackLoop:["runtime observation -> native Issue -> brokered repair -> validation -> deploy -> runtime verification"],stopConditions:["deployment retired"]};
export const maintainMvpReliabilityTemplate:GoalTemplate={id:"maintain-mvp-reliability",version:"1.0.0",system:"mvp-reliability",title:"Maintain MVP Reliability & Product Learning",objective:"Keep the existing MVP healthy and prioritize only reproducible defects or evidence-backed bounded improvements.",recommendedOwnerRole:"engineering",requiredSkills:["goal-contract-execution","bpw-evidence-and-source-discipline"],supportPacks:[{id:"core.evidence-discipline",version:"1.0.0",required:true}],requiredCapabilities:["github","playwright"],inputPaths:["website/**","src/**","app/**","evidence/**"],outputPaths:["validated pull request","product/PRODUCT_LEARNING.md"],acceptanceCriteria:["Runtime reproduction or evidence source retained","Fix passes deterministic validation","Deployed runtime verification succeeds before resolution"],cannotCompleteIf:["Repository is unbound","Write scope is unknown","High-impact change lacks approval","Runtime verification is assumed"],writeScope:["src/**","app/**","website/**","tests/**","*.json","*.yaml","*.toml"],externalActionPolicy:"APPROVAL_REQUIRED_FOR_HIGH_IMPACT",wakeConditions:mvpReliabilitySystem.wakeConditions,nextGoalHints:[],prerequisites:[],evidenceRequirements:["runtime observation or product evidence ID"]};
export const futurePrimaryGoalInterfaces = {
 "observe-product-usage": {measures:["activation","workflow completion","actual MVP use"]},
 "validate-value-realization": {measures:["customer outcome","successful workflow","value achieved"]},
 "validate-retention": {measures:["continued use","repeat","renewal","referral","churn","churn reason"]},
} as const;

export interface ProbeResult {ok:boolean;statusCode?:number;type?:ObservationType;summary:string;endpoint:string;rawSourceReference:string;revision?:string;errorSignature?:string;journey?:"PASS"|"FAIL"|"NOT_RUN"}
export interface ObservationInput extends ProbeResult {observedAt:Date;evidenceIds?:string[];affectedCommit?:string;source?:string;commerciallyBlocking?:boolean}
const redact=(text:string)=>text.replace(/(?:hf_[A-Za-z0-9]{10,}|(?:token|authorization|password)\s*[:=]\s*\S+)/gi,"[REDACTED]");
export function observationFingerprint(input:Pick<ObservationInput,"type"|"endpoint"|"statusCode"|"errorSignature"|"summary">){return createHash("sha256").update([input.type??"HEALTHCHECK_FAILED",input.endpoint,input.statusCode??"",input.errorSignature??input.summary.replace(/\b[0-9a-f]{7,40}\b/gi,"<revision>")].join("|")).digest("hex")}
export function classifySeverity(input:Pick<ObservationInput,"type"|"statusCode"|"commerciallyBlocking">){if(input.type==="DEPLOYMENT_FAILED"||input.type==="STARTUP_ERROR"||input.commerciallyBlocking)return"P0";if(input.statusCode&&input.statusCode>=500||input.type==="VALIDATION_BLOCKER"||input.type==="FUNCTIONAL_REGRESSION")return"P1";if(input.type==="PERFORMANCE_DEGRADATION"||input.type==="ANALYTICS_REGRESSION")return"P2";return"P3"}
export function automaticRepairEligibility(input:{type:ObservationType;severity:string;reproducible:boolean;repositoryBound:boolean;writeScope:string[];highImpact?:boolean;evidenceIds?:string[]}){const repairable=["DEPLOYMENT_FAILED","STARTUP_ERROR","HEALTHCHECK_FAILED","SERVER_ERROR","BROKEN_ROUTE","FUNCTIONAL_REGRESSION","ANALYTICS_REGRESSION","VALIDATION_BLOCKER","USER_REPORTED_DEFECT"];if(input.type==="PRODUCT_LEARNING"&&((input.evidenceIds?.length??0)<2||input.highImpact))return{eligible:false,reason:"Product expansion requires repeated/commercial evidence and managerial approval"};if(input.highImpact)return{eligible:false,reason:"High-impact change requires approval"};if(!input.repositoryBound||!input.reproducible||!input.writeScope.length)return{eligible:false,reason:"Repair lacks repository, reproduction, or bounded write scope"};return{eligible:repairable.includes(input.type)||input.type==="PRODUCT_LEARNING",reason:null}}
export function compileProductLearning(observations:Array<{observationId:string;summary:string;evidenceIds:string[];severity:string;decision?:string|null;issueId?:string|null;verification?:Record<string,unknown>}>){return["# Product Learning","",...observations.map(x=>`## ${x.observationId}\n- Observation: ${x.summary}\n- Evidence: ${x.evidenceIds.join(", ")||"UNKNOWN"}\n- Severity: ${x.severity}\n- Decision: ${x.decision??"PENDING"}\n- Native Issue: ${x.issueId??"NONE"}\n- Verification: ${JSON.stringify(x.verification??{})}`)].join("\n")}

export function mvpReliabilityService(db:Db,hooks:{dispatchRepair?:(input:{companyId:string;issueId:string;repository:string;writeScopes:string[];priority:string})=>Promise<unknown>;probe?:(url:string)=>Promise<ProbeResult>}={}){
 const content=founderosContentService(db);async function activity(companyId:string,action:string,entityId:string,details:Record<string,unknown>){await db.insert(activityLog).values({companyId,actorType:"system",actorId:"mvp-reliability",action,entityType:"deployment",entityId,details})}
 async function registerDeployment(input:{companyId:string;deploymentId:string;repositoryBindingId:string;spaceId:string;spaceUrl:string;runtimeType:string;deploymentRef?:string;healthEndpoint:string;mainEndpoint:string;currentRevision?:string}){if(!/^https:\/\/huggingface\.co\/spaces\//.test(input.spaceUrl))throw new Error("A canonical Hugging Face Space URL is required");if(/token|secret|password|hf_/i.test(JSON.stringify(input)))throw new Error("Deployment metadata must not contain credentials");const binding=await db.select().from(companyRepositoryBindings).where(and(eq(companyRepositoryBindings.id,input.repositoryBindingId),eq(companyRepositoryBindings.companyId,input.companyId),eq(companyRepositoryBindings.active,true))).limit(1).then(r=>r[0]);if(!binding)throw new Error("Active company repository binding required");const existing=await db.select().from(companyDeployments).where(and(eq(companyDeployments.companyId,input.companyId),eq(companyDeployments.deploymentId,input.deploymentId))).limit(1).then(r=>r[0]);if(existing)return{deployment:existing,reused:true};const[deployment]=await db.insert(companyDeployments).values(input).returning();await activity(input.companyId,"mvp.deployment.registered",deployment.id,{spaceId:input.spaceId,repository:binding.repository});return{deployment,reused:false}}
 async function activate(input:{companyId:string;parentGoalId:string;sourceRepository:string;sourceCommit:string}){const goal=await content.instantiateGoal(input.companyId,{repository:input.sourceRepository,commit:input.sourceCommit},maintainMvpReliabilityTemplate,input.parentGoalId);const project=await content.activateSystem(input.companyId,{repository:input.sourceRepository,commit:input.sourceCommit},mvpReliabilitySystem,goal.goal.id,goal.goal.ownerAgentId!);return{goal:goal.goal,project:project.project}}
 async function observe(companyId:string,deploymentId:string,result?:ObservationInput){const deployment=await db.select().from(companyDeployments).where(and(eq(companyDeployments.companyId,companyId),eq(companyDeployments.deploymentId,deploymentId))).limit(1).then(r=>r[0]);if(!deployment)throw new Error("Deployment not found");const observed=result??{...(await hooks.probe!(new URL(deployment.healthEndpoint,deployment.spaceUrl).toString())),observedAt:new Date()};if(observed.ok){await db.update(companyDeployments).set({healthState:"HEALTHY",lastObservedAt:observed.observedAt,lastHealthyAt:observed.observedAt,currentRevision:observed.revision??deployment.currentRevision,updatedAt:new Date()}).where(eq(companyDeployments.id,deployment.id));await activity(companyId,"mvp.runtime.healthy",deployment.id,{statusCode:observed.statusCode,revision:observed.revision});return{healthy:true,julesDispatched:false}}
 const fingerprint=observationFingerprint(observed),severity=classifySeverity(observed),existing=await db.select().from(runtimeObservations).where(and(eq(runtimeObservations.deploymentId,deployment.id),eq(runtimeObservations.errorFingerprint,fingerprint))).limit(1).then(r=>r[0]);if(existing){const[row]=await db.update(runtimeObservations).set({occurrenceCount:existing.occurrenceCount+1,lastSeenAt:observed.observedAt,updatedAt:new Date(),affectedRevision:observed.revision??existing.affectedRevision}).where(eq(runtimeObservations.id,existing.id)).returning();await db.update(companyDeployments).set({healthState:"UNHEALTHY",lastObservedAt:observed.observedAt,updatedAt:new Date()}).where(eq(companyDeployments.id,deployment.id));return{healthy:false,observation:row,deduplicated:true,issueId:row.issueId,julesDispatched:false}}
 const observationId=`obs-${fingerprint.slice(0,16)}`;const[row]=await db.insert(runtimeObservations).values({companyId,deploymentId:deployment.id,observationId,type:observed.type??"HEALTHCHECK_FAILED",severity,source:observed.source??"hf-health",endpoint:observed.endpoint,errorFingerprint:fingerprint,statusCode:observed.statusCode,summary:redact(observed.summary),rawSourceReference:redact(observed.rawSourceReference),evidenceIds:observed.evidenceIds??[],affectedCommit:observed.affectedCommit,affectedRevision:observed.revision,firstSeenAt:observed.observedAt,lastSeenAt:observed.observedAt}).returning();await db.update(companyDeployments).set({healthState:"UNHEALTHY",lastObservedAt:observed.observedAt,updatedAt:new Date()}).where(eq(companyDeployments.id,deployment.id));await activity(companyId,"mvp.runtime.unhealthy",deployment.id,{observationId,severity,julesDispatched:false});return{healthy:false,observation:row,deduplicated:false,julesDispatched:false}}
 async function promote(companyId:string,observationId:string,projectId:string,goalId:string){const observation=await db.select().from(runtimeObservations).where(and(eq(runtimeObservations.companyId,companyId),eq(runtimeObservations.observationId,observationId))).limit(1).then(r=>r[0]);if(!observation)throw new Error("Observation not found");if(observation.issueId)return{issue:await db.select().from(issues).where(eq(issues.id,observation.issueId)).then(r=>r[0]),reused:true};if(observation.type==="PRODUCT_LEARNING"&&observation.evidenceIds.length<2)return{issue:null,decision:"EXPERIMENT_FIRST" as const,reason:"A single speculative request cannot trigger a feature"};const owner=await db.select().from(agents).where(eq(agents.companyId,companyId)).then(rows=>rows.find(a=>/engineering|developer|product/i.test(`${a.title} ${a.role}`)));if(!owner)throw new Error("Native engineering Agent required");const[issue]=await db.insert(issues).values({companyId,projectId,goalId,assigneeAgentId:owner.id,title:`[${observation.severity}] ${observation.summary}`,description:`Runtime observation ${observation.observationId}; deployment ${observation.deploymentId}; endpoint ${observation.endpoint??"unknown"}; revision ${observation.affectedRevision??"unknown"}; evidence ${observation.evidenceIds.join(", ")||"none"}`,status:"todo",priority:observation.severity==="P0"?"critical":observation.severity==="P1"?"high":observation.severity==="P2"?"medium":"low"}).returning();await db.update(runtimeObservations).set({issueId:issue.id,state:"ISSUE_CREATED",decision:observation.type==="PRODUCT_LEARNING"?"SMALL_IMPROVEMENT":"FIX",updatedAt:new Date()}).where(eq(runtimeObservations.id,observation.id));await activity(companyId,"mvp.observation.promoted",observation.id,{issueId:issue.id,priority:issue.priority});return{issue,reused:false}}
 async function dispatch(companyId:string,observationId:string,writeScopes:string[]){const observation=await db.select().from(runtimeObservations).where(and(eq(runtimeObservations.companyId,companyId),eq(runtimeObservations.observationId,observationId))).limit(1).then(r=>r[0]);if(!observation?.issueId)throw new Error("Native Issue required before repair dispatch");if(observation.state==="DISPATCHED")return{dispatched:false,reused:true};const deployment=await db.select().from(companyDeployments).where(eq(companyDeployments.id,observation.deploymentId)).then(r=>r[0]),binding=await db.select().from(companyRepositoryBindings).where(eq(companyRepositoryBindings.id,deployment.repositoryBindingId)).then(r=>r[0]);const eligibility=automaticRepairEligibility({type:observation.type as ObservationType,severity:observation.severity,reproducible:Boolean(observation.endpoint&&observation.rawSourceReference),repositoryBound:Boolean(binding),writeScope:writeScopes,evidenceIds:observation.evidenceIds});if(!eligibility.eligible)return{dispatched:false,reason:eligibility.reason};const result=await hooks.dispatchRepair?.({companyId,issueId:observation.issueId,repository:binding.repository,writeScopes,priority:observation.severity});if(!hooks.dispatchRepair)throw new Error("Existing brokered Jules dispatch hook is required");await db.update(runtimeObservations).set({state:"DISPATCHED",updatedAt:new Date()}).where(eq(runtimeObservations.id,observation.id));return{dispatched:true,result}}
 async function verify(companyId:string,observationId:string,result:ProbeResult){const observation=await db.select().from(runtimeObservations).where(and(eq(runtimeObservations.companyId,companyId),eq(runtimeObservations.observationId,observationId))).limit(1).then(r=>r[0]);if(!observation)throw new Error("Observation not found");const verified=result.ok&&(result.journey??"PASS")!=="FAIL";await db.update(runtimeObservations).set({state:verified?"RESOLVED":"VERIFICATION_PENDING",verification:{checkedAt:new Date().toISOString(),endpoint:result.endpoint,statusCode:result.statusCode,journey:result.journey??"NOT_RUN",revision:result.revision,rawSourceReference:redact(result.rawSourceReference)},updatedAt:new Date()}).where(eq(runtimeObservations.id,observation.id));if(verified&&observation.issueId)await db.update(issues).set({status:"done",completedAt:new Date(),updatedAt:new Date()}).where(eq(issues.id,observation.issueId));await activity(companyId,verified?"mvp.deployment.verified":"mvp.verification.pending",observation.id,{issueId:observation.issueId,revision:result.revision});return{verified,issueResolved:verified&&Boolean(observation.issueId)}}
 async function recordLearning(companyId:string,deploymentId:string,input:Omit<ObservationInput,"ok"|"type">){const result=await observe(companyId,deploymentId,{...input,ok:false,type:"PRODUCT_LEARNING"});for(const artifact of ["offer","value-proposition","demand-experiment","pricing","economics","GTM"])await db.insert(artifactStaleness).values({companyId,artifact,reason:"Product learning may change business assumptions",evidenceId:(result as any).observation.observationId,affectedDependency:"runtime-product-learning"}).onConflictDoNothing();return result}
 return{registerDeployment,activate,observe,promote,dispatch,verify,recordLearning};
}
